// This file is automatically generated. Do not edit manually.
#include "Wrapper/AutoGen/Engine/UPyEngineModuleWrapper.h"
#include "Wrapper/AutoGen/Engine/Struct/UPyWrapperHitResult.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperActor.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperPawn.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperCharacter.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperPlayerController.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperPlayerCameraManager.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperGameInstance.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperWorld.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperGameModeBase.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperActorComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperSceneComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperPrimitiveComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperStaticMeshComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperSkeletalMeshComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperGameplayStatics.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperKismetSystemLibrary.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperKismetMathLibrary.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperInputSettings.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperFXSystemComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperParticleSystemComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperTriggerBase.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperSphereComponent.h"
#include "Wrapper/AutoGen/Engine/Class/UPyWrapperBoxComponent.h"

void InitializeEngineModuleWrapperTypes(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	InitializeUPyWrapperHitResult(ModuleInfo);
	InitializeUPyWrapperActor(ModuleInfo);
	InitializeUPyWrapperPawn(ModuleInfo);
	InitializeUPyWrapperCharacter(ModuleInfo);
	InitializeUPyWrapperPlayerController(ModuleInfo);
	InitializeUPyWrapperPlayerCameraManager(ModuleInfo);
	InitializeUPyWrapperGameInstance(ModuleInfo);
	InitializeUPyWrapperWorld(ModuleInfo);
	InitializeUPyWrapperGameModeBase(ModuleInfo);
	InitializeUPyWrapperActorComponent(ModuleInfo);
	InitializeUPyWrapperSceneComponent(ModuleInfo);
	InitializeUPyWrapperPrimitiveComponent(ModuleInfo);
	InitializeUPyWrapperStaticMeshComponent(ModuleInfo);
	InitializeUPyWrapperSkeletalMeshComponent(ModuleInfo);
	InitializeUPyWrapperGameplayStatics(ModuleInfo);
	InitializeUPyWrapperKismetSystemLibrary(ModuleInfo);
	InitializeUPyWrapperKismetMathLibrary(ModuleInfo);
	InitializeUPyWrapperInputSettings(ModuleInfo);
	InitializeUPyWrapperFXSystemComponent(ModuleInfo);
	InitializeUPyWrapperParticleSystemComponent(ModuleInfo);
	InitializeUPyWrapperTriggerBase(ModuleInfo);
	InitializeUPyWrapperSphereComponent(ModuleInfo);
	InitializeUPyWrapperBoxComponent(ModuleInfo);
}
