// This file is automatically generated. Do not edit manually.
#pragma once

#include "InputCoreTypes.h"
#include "Math/Box2D.h"
#include "Math/Color.h"
#include "Math/Plane.h"
#include "Math/Quat.h"
#include "Math/Rotator.h"
#include "Math/Transform.h"
#include "Math/Vector.h"
#include "Math/Vector2D.h"
#include "Math/Vector4.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"
#include "Utils/UPyGenUtil.h"
#include "Wrapper/AutoGen/CoreUObject/UPyCoreUObjectModuleWrapper.h"
#include "Wrapper/AutoGen/Engine/UPyEngineModuleWrapper.h"
#include "Wrapper/AutoGen/InputCore/UPyInputCoreModuleWrapper.h"
#include "Wrapper/AutoGen/SlateCore/UPySlateCoreModuleWrapper.h"
#include "Wrapper/AutoGen/UMG/UPyUMGModuleWrapper.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"

inline void InitializeAutoGenWrapperTypes(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	InitializeCoreUObjectModuleWrapperTypes(ModuleInfo);
	InitializeEngineModuleWrapperTypes(ModuleInfo);
	InitializeInputCoreModuleWrapperTypes(ModuleInfo);
	InitializeSlateCoreModuleWrapperTypes(ModuleInfo);
	InitializeUMGModuleWrapperTypes(ModuleInfo);
}
