
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "Styling/SlateColor.h"


/** Python type for FUPyWrapperSlateColor */
extern PyTypeObject UPyWrapperSlateColorType;

/** Initialize the UPyWrapperSlateColorType types and add them to the given Python module */
void InitializeUPyWrapperSlateColor(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperSlateColor: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperSlateColorType;
	}

	UNREALPYTHON_API FSlateColor* ValuePtr() const
	{
		return static_cast<FSlateColor*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FSlateColor& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperSlateColor* UPyIsSlateColor(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FSlateColor& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FSlateColor& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
