
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "Layout/Margin.h"


/** Python type for FUPyWrapperMargin */
extern PyTypeObject UPyWrapperMarginType;

/** Initialize the UPyWrapperMarginType types and add them to the given Python module */
void InitializeUPyWrapperMargin(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperMargin: public TUPyWrapperInlineStruct<FMargin>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperMarginType;
	}

	UNREALPYTHON_API FMargin* ValuePtr() const
	{
		return static_cast<FMargin*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FMargin& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperMargin* UPyIsMargin(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FMargin& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FMargin& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
