
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/SlateCore/Struct/UPyWrapperSlateColor.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"
#include "Styling/SlateColor.h"
#include "UObject/NoExportTypes.h"
#include "Styling/StyleColors.h"


PyTypeObject UPyWrapperSlateColorType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"SlateColor", /* tp_name */
	sizeof(FUPyWrapperSlateColor), /* tp_basicsize */
};

struct FGetSets_SlateColor
{
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ColorUseRule()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UScriptStruct* ScriptStruct = TBaseStructure<FSlateColor>::Get())
			{
				if (const FProperty* FoundProperty = ScriptStruct->FindPropertyByName(TEXT("ColorUseRule")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetColorUseRule(FUPyWrapperSlateColor* InSelf, void* InClosure)
	{
		if (!FUPyWrapperSlateColor::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperStruct::GetPropertyValue(InSelf, GetPropertyDef_ColorUseRule(), "ColorUseRule");
	}

	static int SetColorUseRule(FUPyWrapperSlateColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperSlateColor::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperStruct::SetPropertyValue(InSelf, InValue, GetPropertyDef_ColorUseRule(), "ColorUseRule");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_SpecifiedColor()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UScriptStruct* ScriptStruct = TBaseStructure<FSlateColor>::Get())
			{
				if (const FProperty* FoundProperty = ScriptStruct->FindPropertyByName(TEXT("SpecifiedColor")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetSpecifiedColor(FUPyWrapperSlateColor* InSelf, void* InClosure)
	{
		if (!FUPyWrapperSlateColor::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperStruct::GetPropertyValue(InSelf, GetPropertyDef_SpecifiedColor(), "SpecifiedColor");
	}

	static int SetSpecifiedColor(FUPyWrapperSlateColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperSlateColor::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperStruct::SetPropertyValue(InSelf, InValue, GetPropertyDef_SpecifiedColor(), "SpecifiedColor");
	}

};


static PyGetSetDef FUPyWrapperSlateColorGetSets[] = {
	{ UPyCStrCast("ColorUseRule"), (getter)&FGetSets_SlateColor::GetColorUseRule, (setter)&FGetSets_SlateColor::SetColorUseRule, nullptr, nullptr },
	{ UPyCStrCast("SpecifiedColor"), (getter)&FGetSets_SlateColor::GetSpecifiedColor, (setter)&FGetSets_SlateColor::SetSpecifiedColor, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_SlateColor
{
	static int SlateColor_Init_ArgCnt0_Overload0(FUPyWrapperSlateColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		new (InSelf->StructInstance) FSlateColor();
		return 0;
	}


	static int SlateColor_Init_ArgCnt1_Overload0(FUPyWrapperSlateColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		FLinearColor Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			return -1;
		}

		new (InSelf->StructInstance) FSlateColor(Arg0);
		return 0;
	}


	static int SlateColor_Init_ArgCnt1_Overload1(FUPyWrapperSlateColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		FColor Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			return -1;
		}

		new (InSelf->StructInstance) FSlateColor(Arg0);
		return 0;
	}


	static int SlateColor_Init_ArgCnt1_Overload2(FUPyWrapperSlateColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		EStyleColor Arg0;
		if (!UPyConversion::NativizeEnumEntry(PyArg0, StaticEnum<EStyleColor>(), Arg0))
		{
			return -1;
		}

		new (InSelf->StructInstance) FSlateColor(Arg0);
		return 0;
	}


	static int Init(FUPyWrapperSlateColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		const int BaseInit = FUPyWrapperStruct::Init(InSelf);
		if (BaseInit != 0)
		{
			return BaseInit;
		}

		switch (PyTuple_Size(InArgs))
		{
		case 0:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_SlateColor::SlateColor_Init_ArgCnt0_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		case 1:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_SlateColor::SlateColor_Init_ArgCnt1_Overload0)
				|| UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_SlateColor::SlateColor_Init_ArgCnt1_Overload1)
				|| UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_SlateColor::SlateColor_Init_ArgCnt1_Overload2)
			)
			{
				return 0;
			}
			break;
		}
		default:
			break;
		}

		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("SlateColor::__init__"), TEXT("invalid argument"));
		return -1;
	}

	static int SlateColor___eq___CmpAttempt0(FUPyWrapperSlateColor* InSelf, PyObject* InOther)
	{
		FSlateColor Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) == Arg0;
		return bResult ? 1 : 0;
	}

	static int SlateColor___ne___CmpAttempt0(FUPyWrapperSlateColor* InSelf, PyObject* InOther)
	{
		FSlateColor Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) != Arg0;
		return bResult ? 1 : 0;
	}

	static PyObject* RichCmp(FUPyWrapperSlateColor* InSelf, PyObject* InOther, int InOp)
	{
		bool bHandled = false;
		bool bResult = false;
		switch (InOp)
		{
		case Py_EQ:
		{
			if (!bHandled)
			{
				int AttemptResult = SlateColor___eq___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
				else
				{
					PyErr_Clear();
				}
			}
			break;
		}
		case Py_NE:
		{
			if (!bHandled)
			{
				int AttemptResult = SlateColor___ne___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
				else
				{
					PyErr_Clear();
				}
			}
			break;
		}
		default:
			break;
		}
		if (!bHandled)
		{
			Py_RETURN_NOTIMPLEMENTED;
		}
		if (bResult)
		{
			Py_RETURN_TRUE;
		}
		Py_RETURN_FALSE;
	}
};


struct FMethods_SlateColor
{
	static PyObject* CallGetSpecifiedColor(FUPyWrapperSlateColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetSpecifiedColor();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallIsColorSpecified(FUPyWrapperSlateColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsColorSpecified();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallUseForeground(FUPyWrapperSlateColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = FSlateColor::UseForeground();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallUseSubduedForeground(FUPyWrapperSlateColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = FSlateColor::UseSubduedForeground();
		return UPyConversion::PythonizeStructInstance(Result);
	}

};


static PyMethodDef FUPyWrapperSlateColorPyMethodDefs[] = {
	{ "GetSpecifiedColor", UPyCFunctionCast(&FMethods_SlateColor::CallGetSpecifiedColor), METH_NOARGS, nullptr },
	{ "IsColorSpecified", UPyCFunctionCast(&FMethods_SlateColor::CallIsColorSpecified), METH_NOARGS, nullptr },
	{ "UseForeground", UPyCFunctionCast(&FMethods_SlateColor::CallUseForeground), METH_NOARGS | METH_STATIC, nullptr },
	{ "UseSubduedForeground", UPyCFunctionCast(&FMethods_SlateColor::CallUseSubduedForeground), METH_NOARGS | METH_STATIC, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperSlateColor(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperSlateColorType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_SlateColor::Init;
	PyType->tp_methods = FUPyWrapperSlateColorPyMethodDefs;
	PyType->tp_getset = FUPyWrapperSlateColorGetSets;
	PyType->tp_richcompare = (richcmpfunc)&FFuncs_SlateColor::RichCmp;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperSlateColor(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FSlateColor>::Get(), DoInitWrapperSlateColor);
}

PyObject* FUPyWrapperSlateColor::CreateInstance(const FSlateColor& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperSlateColorType, TBaseStructure<FSlateColor>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperSlateColor* UPyIsSlateColor(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperSlateColorType))
	{
		return (FUPyWrapperSlateColor*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FSlateColor& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperSlateColor* PyVector = UPyIsSlateColor(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FSlateColor'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
	
	FUPyConversionResult PythonizeStructInstance(const FSlateColor& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperSlateColor::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
