
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "Styling/SlateBrush.h"


/** Python type for FUPyWrapperSlateBrush */
extern PyTypeObject UPyWrapperSlateBrushType;

/** Initialize the UPyWrapperSlateBrushType types and add them to the given Python module */
void InitializeUPyWrapperSlateBrush(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperSlateBrush: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperSlateBrushType;
	}

	UNREALPYTHON_API FSlateBrush* ValuePtr() const
	{
		return static_cast<FSlateBrush*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FSlateBrush& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperSlateBrush* UPyIsSlateBrush(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FSlateBrush& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FSlateBrush& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
