
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Engine/Class/UPyWrapperWorld.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "WorldPartition/DataLayer/DataLayerManager.h"
#include "Helper/UPyRuntimeScriptExportHelperLibrary.h"
#include "GameFramework/WorldSettings.h"


PyTypeObject UPyWrapperWorldType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"World", /* tp_name */
	sizeof(FUPyWrapperWorld), /* tp_basicsize */
};

struct FGetSets_World
{
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AISystem()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AISystem")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAISystem(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_AISystem(), "AISystem");
	}

	static int SetAISystem(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_AISystem(), "AISystem");
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ActiveGroupActors()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ActiveGroupActors")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetActiveGroupActors(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->ActiveGroupActors, CastField<FArrayProperty>(GetPropertyDef_ActiveGroupActors().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetActiveGroupActors(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ActiveGroupActors(), "ActiveGroupActors");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AuthorityGameMode()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AuthorityGameMode")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAuthorityGameMode(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_AuthorityGameMode(), "AuthorityGameMode");
	}

	static int SetAuthorityGameMode(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_AuthorityGameMode(), "AuthorityGameMode");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AvoidanceManager()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AvoidanceManager")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAvoidanceManager(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_AvoidanceManager(), "AvoidanceManager");
	}

	static int SetAvoidanceManager(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_AvoidanceManager(), "AvoidanceManager");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CanvasForDrawMaterialToRenderTarget()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CanvasForDrawMaterialToRenderTarget")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCanvasForDrawMaterialToRenderTarget(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_CanvasForDrawMaterialToRenderTarget(), "CanvasForDrawMaterialToRenderTarget");
	}

	static int SetCanvasForDrawMaterialToRenderTarget(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_CanvasForDrawMaterialToRenderTarget(), "CanvasForDrawMaterialToRenderTarget");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CanvasForRenderingToTarget()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CanvasForRenderingToTarget")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCanvasForRenderingToTarget(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_CanvasForRenderingToTarget(), "CanvasForRenderingToTarget");
	}

	static int SetCanvasForRenderingToTarget(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_CanvasForRenderingToTarget(), "CanvasForRenderingToTarget");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedEndOfFrameMarkRenderStateDirty()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedEndOfFrameMarkRenderStateDirty")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedEndOfFrameMarkRenderStateDirty(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedEndOfFrameMarkRenderStateDirty(), "ComponentsThatNeedEndOfFrameMarkRenderStateDirty");
	}

	static int SetComponentsThatNeedEndOfFrameMarkRenderStateDirty(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedEndOfFrameMarkRenderStateDirty(), "ComponentsThatNeedEndOfFrameMarkRenderStateDirty");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedEndOfFrameUpdate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedEndOfFrameUpdate(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate(), "ComponentsThatNeedEndOfFrameUpdate");
	}

	static int SetComponentsThatNeedEndOfFrameUpdate(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate(), "ComponentsThatNeedEndOfFrameUpdate");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_AsyncTick()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedEndOfFrameUpdate_AsyncTick")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedEndOfFrameUpdate_AsyncTick(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_AsyncTick(), "ComponentsThatNeedEndOfFrameUpdate_AsyncTick");
	}

	static int SetComponentsThatNeedEndOfFrameUpdate_AsyncTick(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_AsyncTick(), "ComponentsThatNeedEndOfFrameUpdate_AsyncTick");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_OnGameThread()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedEndOfFrameUpdate_OnGameThread")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedEndOfFrameUpdate_OnGameThread(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_OnGameThread(), "ComponentsThatNeedEndOfFrameUpdate_OnGameThread");
	}

	static int SetComponentsThatNeedEndOfFrameUpdate_OnGameThread(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedEndOfFrameUpdate_OnGameThread(), "ComponentsThatNeedEndOfFrameUpdate_OnGameThread");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedPreEndOfFrameSync")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedPreEndOfFrameSync(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync(), "ComponentsThatNeedPreEndOfFrameSync");
	}

	static int SetComponentsThatNeedPreEndOfFrameSync(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync(), "ComponentsThatNeedPreEndOfFrameSync");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync_AsyncTick()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ComponentsThatNeedPreEndOfFrameSync_AsyncTick")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetComponentsThatNeedPreEndOfFrameSync_AsyncTick(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync_AsyncTick(), "ComponentsThatNeedPreEndOfFrameSync_AsyncTick");
	}

	static int SetComponentsThatNeedPreEndOfFrameSync_AsyncTick(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ComponentsThatNeedPreEndOfFrameSync_AsyncTick(), "ComponentsThatNeedPreEndOfFrameSync_AsyncTick");
	}

	static PyObject* GetContentBundleManager(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ContentBundleManager);
	}

	static int SetContentBundleManager(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ContentBundleManager))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::ContentBundleManager"), TEXT("value is not a compatible object"));
		return -1;
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CurrentLevel()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CurrentLevel")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCurrentLevel(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_CurrentLevel(), "CurrentLevel");
	}

	static int SetCurrentLevel(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_CurrentLevel(), "CurrentLevel");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_DefaultPhysicsVolume()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("DefaultPhysicsVolume")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetDefaultPhysicsVolume(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_DefaultPhysicsVolume(), "DefaultPhysicsVolume");
	}

	static int SetDefaultPhysicsVolume(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_DefaultPhysicsVolume(), "DefaultPhysicsVolume");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_DemoNetDriver()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("DemoNetDriver")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetDemoNetDriver(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_DemoNetDriver(), "DemoNetDriver");
	}

	static int SetDemoNetDriver(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_DemoNetDriver(), "DemoNetDriver");
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_EditorViews()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("EditorViews")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetEditorViews(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->EditorViews, CastField<FArrayProperty>(GetPropertyDef_EditorViews().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetEditorViews(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_EditorViews(), "EditorViews");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ExtraReferencedObjects()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ExtraReferencedObjects")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetExtraReferencedObjects(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->ExtraReferencedObjects, CastField<FArrayProperty>(GetPropertyDef_ExtraReferencedObjects().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetExtraReferencedObjects(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ExtraReferencedObjects(), "ExtraReferencedObjects");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_GameState()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("GameState")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetGameState(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_GameState(), "GameState");
	}

	static int SetGameState(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_GameState(), "GameState");
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_Layers()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("Layers")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetLayers(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->Layers, CastField<FArrayProperty>(GetPropertyDef_Layers().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetLayers(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_Layers(), "Layers");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_LevelCollections()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("LevelCollections")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetLevelCollections(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_LevelCollections(), "LevelCollections");
	}

	static int SetLevelCollections(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_LevelCollections(), "LevelCollections");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_Levels()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("Levels")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetLevels(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_Levels(), "Levels");
	}

	static int SetLevels(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_Levels(), "Levels");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_LineBatchers()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("LineBatchers")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetLineBatchers(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_LineBatchers(), "LineBatchers");
	}

	static int SetLineBatchers(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_LineBatchers(), "LineBatchers");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_MakingInvisibleLevels()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("MakingInvisibleLevels")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetMakingInvisibleLevels(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_MakingInvisibleLevels(), "MakingInvisibleLevels");
	}

	static int SetMakingInvisibleLevels(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_MakingInvisibleLevels(), "MakingInvisibleLevels");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_MakingVisibleLevels()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("MakingVisibleLevels")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetMakingVisibleLevels(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_MakingVisibleLevels(), "MakingVisibleLevels");
	}

	static int SetMakingVisibleLevels(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_MakingVisibleLevels(), "MakingVisibleLevels");
	}

	static PyObject* GetMyParticleEventManager(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->MyParticleEventManager);
	}

	static int SetMyParticleEventManager(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->MyParticleEventManager))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::MyParticleEventManager"), TEXT("value is not a compatible object"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_NavigationSystem()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("NavigationSystem")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetNavigationSystem(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_NavigationSystem(), "NavigationSystem");
	}

	static int SetNavigationSystem(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_NavigationSystem(), "NavigationSystem");
	}

	static PyObject* GetNetDriver(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->NetDriver);
	}

	static int SetNetDriver(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->NetDriver))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::NetDriver"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetNetworkManager(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->NetworkManager);
	}

	static int SetNetworkManager(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->NetworkManager))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::NetworkManager"), TEXT("value is not a compatible object"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_OwningGameInstance()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("OwningGameInstance")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetOwningGameInstance(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_OwningGameInstance(), "OwningGameInstance");
	}

	static int SetOwningGameInstance(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_OwningGameInstance(), "OwningGameInstance");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_PSCPool()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("PSCPool")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetPSCPool(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_PSCPool(), "PSCPool");
	}

	static int SetPSCPool(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_PSCPool(), "PSCPool");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ParameterCollectionInstances()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ParameterCollectionInstances")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetParameterCollectionInstances(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ParameterCollectionInstances(), "ParameterCollectionInstances");
	}

	static int SetParameterCollectionInstances(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ParameterCollectionInstances(), "ParameterCollectionInstances");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_PerModuleDataObjects()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("PerModuleDataObjects")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetPerModuleDataObjects(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->PerModuleDataObjects, CastField<FArrayProperty>(GetPropertyDef_PerModuleDataObjects().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetPerModuleDataObjects(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_PerModuleDataObjects(), "PerModuleDataObjects");
	}

	static PyObject* GetPersistentLevel(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->PersistentLevel);
	}

	static int SetPersistentLevel(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->PersistentLevel))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::PersistentLevel"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetPhysicsCollisionHandler(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->PhysicsCollisionHandler);
	}

	static int SetPhysicsCollisionHandler(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->PhysicsCollisionHandler))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::PhysicsCollisionHandler"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetPhysicsField(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->PhysicsField);
	}

	static int SetPhysicsField(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->PhysicsField))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::PhysicsField"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetPhysicsQueryHandler(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->PhysicsQueryHandler);
	}

	static int SetPhysicsQueryHandler(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->PhysicsQueryHandler))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::PhysicsQueryHandler"), TEXT("value is not a compatible object"));
		return -1;
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_SelectedLevels()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("SelectedLevels")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetSelectedLevels(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_SelectedLevels(), "SelectedLevels");
	}

	static int SetSelectedLevels(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_SelectedLevels(), "SelectedLevels");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ServerStreamingLevelsVisibility()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ServerStreamingLevelsVisibility")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetServerStreamingLevelsVisibility(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_ServerStreamingLevelsVisibility(), "ServerStreamingLevelsVisibility");
	}

	static int SetServerStreamingLevelsVisibility(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_ServerStreamingLevelsVisibility(), "ServerStreamingLevelsVisibility");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_StreamingLevels()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("StreamingLevels")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetStreamingLevels(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_StreamingLevels(), "StreamingLevels");
	}

	static int SetStreamingLevels(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_StreamingLevels(), "StreamingLevels");
	}

	static PyObject* GetStreamingLevelsPrefix(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->StreamingLevelsPrefix);
	}

	static int SetStreamingLevelsPrefix(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->StreamingLevelsPrefix))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::StreamingLevelsPrefix"), TEXT("value is not a string"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_StreamingLevelsToConsider()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWorld::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("StreamingLevelsToConsider")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetStreamingLevelsToConsider(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_StreamingLevelsToConsider(), "StreamingLevelsToConsider");
	}

	static int SetStreamingLevelsToConsider(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_StreamingLevelsToConsider(), "StreamingLevelsToConsider");
	}

#if WITH_EDITOR
	static PyObject* GetThumbnailInfo(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ThumbnailInfo);
	}

	static int SetThumbnailInfo(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ThumbnailInfo))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::ThumbnailInfo"), TEXT("value is not a compatible object"));
		return -1;
	}

#endif
	static PyObject* GetWorldComposition(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->WorldComposition);
	}

	static int SetWorldComposition(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->WorldComposition))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::WorldComposition"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetbAreConstraintsDirty(FUPyWrapperWorld* InSelf, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bAreConstraintsDirty);
	}

	static int SetbAreConstraintsDirty(FUPyWrapperWorld* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperWorld::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bAreConstraintsDirty = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("World::bAreConstraintsDirty"), TEXT("value is not bool"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperWorldGetSets[] = {
	{ UPyCStrCast("AISystem"), (getter)&FGetSets_World::GetAISystem, (setter)&FGetSets_World::SetAISystem, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("ActiveGroupActors"), (getter)&FGetSets_World::GetActiveGroupActors, (setter)&FGetSets_World::SetActiveGroupActors, nullptr, nullptr },
#endif
	{ UPyCStrCast("AuthorityGameMode"), (getter)&FGetSets_World::GetAuthorityGameMode, (setter)&FGetSets_World::SetAuthorityGameMode, nullptr, nullptr },
	{ UPyCStrCast("AvoidanceManager"), (getter)&FGetSets_World::GetAvoidanceManager, (setter)&FGetSets_World::SetAvoidanceManager, nullptr, nullptr },
	{ UPyCStrCast("CanvasForDrawMaterialToRenderTarget"), (getter)&FGetSets_World::GetCanvasForDrawMaterialToRenderTarget, (setter)&FGetSets_World::SetCanvasForDrawMaterialToRenderTarget, nullptr, nullptr },
	{ UPyCStrCast("CanvasForRenderingToTarget"), (getter)&FGetSets_World::GetCanvasForRenderingToTarget, (setter)&FGetSets_World::SetCanvasForRenderingToTarget, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedEndOfFrameMarkRenderStateDirty"), (getter)&FGetSets_World::GetComponentsThatNeedEndOfFrameMarkRenderStateDirty, (setter)&FGetSets_World::SetComponentsThatNeedEndOfFrameMarkRenderStateDirty, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedEndOfFrameUpdate"), (getter)&FGetSets_World::GetComponentsThatNeedEndOfFrameUpdate, (setter)&FGetSets_World::SetComponentsThatNeedEndOfFrameUpdate, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedEndOfFrameUpdate_AsyncTick"), (getter)&FGetSets_World::GetComponentsThatNeedEndOfFrameUpdate_AsyncTick, (setter)&FGetSets_World::SetComponentsThatNeedEndOfFrameUpdate_AsyncTick, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedEndOfFrameUpdate_OnGameThread"), (getter)&FGetSets_World::GetComponentsThatNeedEndOfFrameUpdate_OnGameThread, (setter)&FGetSets_World::SetComponentsThatNeedEndOfFrameUpdate_OnGameThread, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedPreEndOfFrameSync"), (getter)&FGetSets_World::GetComponentsThatNeedPreEndOfFrameSync, (setter)&FGetSets_World::SetComponentsThatNeedPreEndOfFrameSync, nullptr, nullptr },
	{ UPyCStrCast("ComponentsThatNeedPreEndOfFrameSync_AsyncTick"), (getter)&FGetSets_World::GetComponentsThatNeedPreEndOfFrameSync_AsyncTick, (setter)&FGetSets_World::SetComponentsThatNeedPreEndOfFrameSync_AsyncTick, nullptr, nullptr },
	{ UPyCStrCast("ContentBundleManager"), (getter)&FGetSets_World::GetContentBundleManager, (setter)&FGetSets_World::SetContentBundleManager, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("CurrentLevel"), (getter)&FGetSets_World::GetCurrentLevel, (setter)&FGetSets_World::SetCurrentLevel, nullptr, nullptr },
#endif
	{ UPyCStrCast("DefaultPhysicsVolume"), (getter)&FGetSets_World::GetDefaultPhysicsVolume, (setter)&FGetSets_World::SetDefaultPhysicsVolume, nullptr, nullptr },
	{ UPyCStrCast("DemoNetDriver"), (getter)&FGetSets_World::GetDemoNetDriver, (setter)&FGetSets_World::SetDemoNetDriver, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("EditorViews"), (getter)&FGetSets_World::GetEditorViews, (setter)&FGetSets_World::SetEditorViews, nullptr, nullptr },
#endif
	{ UPyCStrCast("ExtraReferencedObjects"), (getter)&FGetSets_World::GetExtraReferencedObjects, (setter)&FGetSets_World::SetExtraReferencedObjects, nullptr, nullptr },
	{ UPyCStrCast("GameState"), (getter)&FGetSets_World::GetGameState, (setter)&FGetSets_World::SetGameState, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("Layers"), (getter)&FGetSets_World::GetLayers, (setter)&FGetSets_World::SetLayers, nullptr, nullptr },
#endif
	{ UPyCStrCast("LevelCollections"), (getter)&FGetSets_World::GetLevelCollections, (setter)&FGetSets_World::SetLevelCollections, nullptr, nullptr },
	{ UPyCStrCast("Levels"), (getter)&FGetSets_World::GetLevels, (setter)&FGetSets_World::SetLevels, nullptr, nullptr },
	{ UPyCStrCast("LineBatchers"), (getter)&FGetSets_World::GetLineBatchers, (setter)&FGetSets_World::SetLineBatchers, nullptr, nullptr },
	{ UPyCStrCast("MakingInvisibleLevels"), (getter)&FGetSets_World::GetMakingInvisibleLevels, (setter)&FGetSets_World::SetMakingInvisibleLevels, nullptr, nullptr },
	{ UPyCStrCast("MakingVisibleLevels"), (getter)&FGetSets_World::GetMakingVisibleLevels, (setter)&FGetSets_World::SetMakingVisibleLevels, nullptr, nullptr },
	{ UPyCStrCast("MyParticleEventManager"), (getter)&FGetSets_World::GetMyParticleEventManager, (setter)&FGetSets_World::SetMyParticleEventManager, nullptr, nullptr },
	{ UPyCStrCast("NavigationSystem"), (getter)&FGetSets_World::GetNavigationSystem, (setter)&FGetSets_World::SetNavigationSystem, nullptr, nullptr },
	{ UPyCStrCast("NetDriver"), (getter)&FGetSets_World::GetNetDriver, (setter)&FGetSets_World::SetNetDriver, nullptr, nullptr },
	{ UPyCStrCast("NetworkManager"), (getter)&FGetSets_World::GetNetworkManager, (setter)&FGetSets_World::SetNetworkManager, nullptr, nullptr },
	{ UPyCStrCast("OwningGameInstance"), (getter)&FGetSets_World::GetOwningGameInstance, (setter)&FGetSets_World::SetOwningGameInstance, nullptr, nullptr },
	{ UPyCStrCast("PSCPool"), (getter)&FGetSets_World::GetPSCPool, (setter)&FGetSets_World::SetPSCPool, nullptr, nullptr },
	{ UPyCStrCast("ParameterCollectionInstances"), (getter)&FGetSets_World::GetParameterCollectionInstances, (setter)&FGetSets_World::SetParameterCollectionInstances, nullptr, nullptr },
	{ UPyCStrCast("PerModuleDataObjects"), (getter)&FGetSets_World::GetPerModuleDataObjects, (setter)&FGetSets_World::SetPerModuleDataObjects, nullptr, nullptr },
	{ UPyCStrCast("PersistentLevel"), (getter)&FGetSets_World::GetPersistentLevel, (setter)&FGetSets_World::SetPersistentLevel, nullptr, nullptr },
	{ UPyCStrCast("PhysicsCollisionHandler"), (getter)&FGetSets_World::GetPhysicsCollisionHandler, (setter)&FGetSets_World::SetPhysicsCollisionHandler, nullptr, nullptr },
	{ UPyCStrCast("PhysicsField"), (getter)&FGetSets_World::GetPhysicsField, (setter)&FGetSets_World::SetPhysicsField, nullptr, nullptr },
	{ UPyCStrCast("PhysicsQueryHandler"), (getter)&FGetSets_World::GetPhysicsQueryHandler, (setter)&FGetSets_World::SetPhysicsQueryHandler, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("SelectedLevels"), (getter)&FGetSets_World::GetSelectedLevels, (setter)&FGetSets_World::SetSelectedLevels, nullptr, nullptr },
#endif
	{ UPyCStrCast("ServerStreamingLevelsVisibility"), (getter)&FGetSets_World::GetServerStreamingLevelsVisibility, (setter)&FGetSets_World::SetServerStreamingLevelsVisibility, nullptr, nullptr },
	{ UPyCStrCast("StreamingLevels"), (getter)&FGetSets_World::GetStreamingLevels, (setter)&FGetSets_World::SetStreamingLevels, nullptr, nullptr },
	{ UPyCStrCast("StreamingLevelsPrefix"), (getter)&FGetSets_World::GetStreamingLevelsPrefix, (setter)&FGetSets_World::SetStreamingLevelsPrefix, nullptr, nullptr },
	{ UPyCStrCast("StreamingLevelsToConsider"), (getter)&FGetSets_World::GetStreamingLevelsToConsider, (setter)&FGetSets_World::SetStreamingLevelsToConsider, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("ThumbnailInfo"), (getter)&FGetSets_World::GetThumbnailInfo, (setter)&FGetSets_World::SetThumbnailInfo, nullptr, nullptr },
#endif
	{ UPyCStrCast("WorldComposition"), (getter)&FGetSets_World::GetWorldComposition, (setter)&FGetSets_World::SetWorldComposition, nullptr, nullptr },
	{ UPyCStrCast("bAreConstraintsDirty"), (getter)&FGetSets_World::GetbAreConstraintsDirty, (setter)&FGetSets_World::SetbAreConstraintsDirty, nullptr, nullptr },
	{ nullptr }
};



struct FMethods_World
{
	static PyObject* CallGetDataLayerManager(FUPyWrapperWorld* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetDataLayerManager();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetNetMode(FUPyWrapperWorld* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = UUPyRuntimeScriptExportHelperLibrary::World_GetNetMode(InSelf->ValuePtr());
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetNetModeName(FUPyWrapperWorld* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = UUPyRuntimeScriptExportHelperLibrary::World_GetNetModeName(InSelf->ValuePtr());
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallHandleTimelineScrubbed(FUPyWrapperWorld* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->HandleTimelineScrubbed();
		Py_RETURN_NONE;
	}

	static PyObject* CallK2_GetWorldSettings(FUPyWrapperWorld* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->K2_GetWorldSettings();
		return UPyConversion::Pythonize(Result);
	}

};


static PyMethodDef FUPyWrapperWorldPyMethodDefs[] = {
	{ "GetDataLayerManager", UPyCFunctionCast(&FMethods_World::CallGetDataLayerManager), METH_NOARGS, nullptr },
	{ "GetNetMode", UPyCFunctionCast(&FMethods_World::CallGetNetMode), METH_NOARGS, nullptr },
	{ "GetNetModeName", UPyCFunctionCast(&FMethods_World::CallGetNetModeName), METH_NOARGS, nullptr },
	{ "HandleTimelineScrubbed", UPyCFunctionCast(&FMethods_World::CallHandleTimelineScrubbed), METH_NOARGS, nullptr },
	{ "K2_GetWorldSettings", UPyCFunctionCast(&FMethods_World::CallK2_GetWorldSettings), METH_NOARGS, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperWorld(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperWorldType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperWorldPyMethodDefs;
	PyType->tp_getset = FUPyWrapperWorldGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperWorld(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UWorld::StaticClass(), DoInitWrapperWorld);
}

FUPyWrapperWorld* UPyIsWorld(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperWorldType))
	{
		return (FUPyWrapperWorld*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UWorld*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperWorld* PyWorld = UPyIsWorld(PyObj))
		{
			if (!FUPyWrapperObject::ValidateInternalState(PyWorld))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyWorld->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UWorld'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
