
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "GameFramework/GameStateBase.h"


/** Python type for FUPyWrapperGameStateBase */
extern PyTypeObject UPyWrapperGameStateBaseType;

/** Initialize the UPyWrapperGameStateBaseType types and add them to the given Python module */
void InitializeUPyWrapperGameStateBase(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperGameStateBase: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperGameStateBaseType;
	}

	UNREALPYTHON_API AGameStateBase* ValuePtr() const
	{
		return Cast<AGameStateBase>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperGameStateBase* UPyIsGameStateBase(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, AGameStateBase*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
