
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "GameFramework/Controller.h"


/** Python type for FUPyWrapperController */
extern PyTypeObject UPyWrapperControllerType;

/** Initialize the UPyWrapperControllerType types and add them to the given Python module */
void InitializeUPyWrapperController(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperController: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperControllerType;
	}

	UNREALPYTHON_API AController* ValuePtr() const
	{
		return Cast<AController>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperController* UPyIsController(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, AController*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
