// Copyright Epic Games, Inc. All Rights Reserved.

// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Engine/Class/UPyWrapperFXSystemComponent.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Particles/ParticleSystem.h"
#include "GameFramework/Actor.h"
#include "Components/SceneComponent.h"
#include "Engine/EngineTypes.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperFXSystemComponentType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"FXSystemComponent", /* tp_name */
	sizeof(FUPyWrapperFXSystemComponent), /* tp_basicsize */
};




struct FMethods_FXSystemComponent
{
	static PyObject* CallGetFXSystemAsset(FUPyWrapperFXSystemComponent* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetFXSystemAsset();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallReleaseToPool(FUPyWrapperFXSystemComponent* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->ReleaseToPool();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetActorParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetActorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		AActor* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetActorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetActorParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetAutoAttachmentParameters(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		USceneComponent* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetAutoAttachmentParameters"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FName Arg1;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetAutoAttachmentParameters"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		EAttachmentRule Arg2;
		if (!UPyConversion::NativizeEnumEntry(PyArg2, StaticEnum<EAttachmentRule>(), Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetAutoAttachmentParameters"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		EAttachmentRule Arg3;
		if (!UPyConversion::NativizeEnumEntry(PyArg3, StaticEnum<EAttachmentRule>(), Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetAutoAttachmentParameters"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = PyTuple_GetItem(InArgs, 4);
		if (PyArg4 == nullptr)
		{
			return nullptr;
		}
		EAttachmentRule Arg4;
		if (!UPyConversion::NativizeEnumEntry(PyArg4, StaticEnum<EAttachmentRule>(), Arg4))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetAutoAttachmentParameters"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetAutoAttachmentParameters(Arg0, Arg1, Arg2, Arg3, Arg4);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetBoolParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetBoolParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		bool Arg1 = false;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetBoolParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetBoolParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetColorParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetColorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FLinearColor Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetColorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetColorParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetEmitterEnable(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetEmitterEnable"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		bool Arg1 = false;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetEmitterEnable"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetEmitterEnable(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetFloatParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetFloatParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		float Arg1 = 0.0f;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetFloatParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetFloatParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetIntParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetIntParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		int32 Arg1 = 0;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetIntParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetIntParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetUseAutoManageAttachment(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		bool Arg0 = false;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetUseAutoManageAttachment"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetUseAutoManageAttachment(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetVectorParameter(FUPyWrapperFXSystemComponent* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FName Arg0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetVectorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("FXSystemComponent::SetVectorParameter"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetVectorParameter(Arg0, Arg1);
		Py_RETURN_NONE;
	}

};


static PyMethodDef FUPyWrapperFXSystemComponentPyMethodDefs[] = {
	{ "GetFXSystemAsset", UPyCFunctionCast(&FMethods_FXSystemComponent::CallGetFXSystemAsset), METH_NOARGS, nullptr },
	{ "ReleaseToPool", UPyCFunctionCast(&FMethods_FXSystemComponent::CallReleaseToPool), METH_NOARGS, nullptr },
	{ "SetActorParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetActorParameter), METH_VARARGS, nullptr },
	{ "SetAutoAttachmentParameters", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetAutoAttachmentParameters), METH_VARARGS, nullptr },
	{ "SetBoolParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetBoolParameter), METH_VARARGS, nullptr },
	{ "SetColorParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetColorParameter), METH_VARARGS, nullptr },
	{ "SetEmitterEnable", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetEmitterEnable), METH_VARARGS, nullptr },
	{ "SetFloatParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetFloatParameter), METH_VARARGS, nullptr },
	{ "SetIntParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetIntParameter), METH_VARARGS, nullptr },
	{ "SetUseAutoManageAttachment", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetUseAutoManageAttachment), METH_O, nullptr },
	{ "SetVectorParameter", UPyCFunctionCast(&FMethods_FXSystemComponent::CallSetVectorParameter), METH_VARARGS, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperFXSystemComponent(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperFXSystemComponentType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperFXSystemComponentPyMethodDefs;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperFXSystemComponent(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UFXSystemComponent::StaticClass(), DoInitWrapperFXSystemComponent);
}

FUPyWrapperFXSystemComponent* UPyIsFXSystemComponent(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperFXSystemComponentType))
	{
		return (FUPyWrapperFXSystemComponent*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UFXSystemComponent*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperFXSystemComponent* PyFXSystemComponent = UPyIsFXSystemComponent(PyObj))
		{
			OutVal = PyFXSystemComponent->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UFXSystemComponent'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
