
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "GameFramework/GameModeBase.h"


/** Python type for FUPyWrapperGameModeBase */
extern PyTypeObject UPyWrapperGameModeBaseType;

/** Initialize the UPyWrapperGameModeBaseType types and add them to the given Python module */
void InitializeUPyWrapperGameModeBase(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperGameModeBase: public FUPyWrapperObjectBase 
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperGameModeBaseType;
	}

	UNREALPYTHON_API AGameModeBase* ValuePtr() const
	{
		return Cast<AGameModeBase>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperGameModeBase* UPyIsGameModeBase(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, AGameModeBase*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
