
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/SphereComponent.h"


/** Python type for FUPyWrapperSphereComponent */
extern PyTypeObject UPyWrapperSphereComponentType;

/** Initialize the UPyWrapperSphereComponentType types and add them to the given Python module */
void InitializeUPyWrapperSphereComponent(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperSphereComponent: public FUPyWrapperObjectBase 
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperSphereComponentType;
	}

	UNREALPYTHON_API USphereComponent* ValuePtr() const
	{
		return Cast<USphereComponent>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperSphereComponent* UPyIsSphereComponent(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, USphereComponent*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
