
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Engine/Texture2D.h"


/** Python type for FUPyWrapperTexture2D */
extern PyTypeObject UPyWrapperTexture2DType;

/** Initialize the UPyWrapperTexture2DType types and add them to the given Python module */
void InitializeUPyWrapperTexture2D(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperTexture2D: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperTexture2DType;
	}

	UNREALPYTHON_API UTexture2D* ValuePtr() const
	{
		return Cast<UTexture2D>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperTexture2D* UPyIsTexture2D(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UTexture2D*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
