
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Engine/Class/UPyWrapperEngineTypes.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"


PyTypeObject UPyWrapperEngineTypesType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"EngineTypes", /* tp_name */
	sizeof(FUPyWrapperEngineTypes), /* tp_basicsize */
};







PyTypeObject* DoInitWrapperEngineTypes(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperEngineTypesType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperEngineTypes(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UEngineTypes::StaticClass(), DoInitWrapperEngineTypes);
}

FUPyWrapperEngineTypes* UPyIsEngineTypes(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperEngineTypesType))
	{
		return (FUPyWrapperEngineTypes*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UEngineTypes*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperEngineTypes* PyEngineTypes = UPyIsEngineTypes(PyObj))
		{
			if (!FUPyWrapperObject::ValidateInternalState(PyEngineTypes))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyEngineTypes->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UEngineTypes'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
