
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "GameFramework/CharacterMovementComponent.h"


/** Python type for FUPyWrapperCharacterMovementComponent */
extern PyTypeObject UPyWrapperCharacterMovementComponentType;

/** Initialize the UPyWrapperCharacterMovementComponentType types and add them to the given Python module */
void InitializeUPyWrapperCharacterMovementComponent(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperCharacterMovementComponent: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperCharacterMovementComponentType;
	}

	UNREALPYTHON_API UCharacterMovementComponent* ValuePtr() const
	{
		return Cast<UCharacterMovementComponent>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperCharacterMovementComponent* UPyIsCharacterMovementComponent(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UCharacterMovementComponent*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
