
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Engine/Class/UPyWrapperPlayerCameraManager.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "UObject/Class.h"
#include "Camera/CameraModifier.h"
#include "GameFramework/Actor.h"
#include "UObject/NoExportTypes.h"
#include "GameFramework/PlayerController.h"
#include "Camera/CameraTypes.h"
#include "Camera/CameraShakeBase.h"
#include "Camera/CameraShakeSourceComponent.h"


PyTypeObject UPyWrapperPlayerCameraManagerType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"PlayerCameraManager", /* tp_name */
	sizeof(FUPyWrapperPlayerCameraManager), /* tp_basicsize */
};

struct FGetSets_PlayerCameraManager
{
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AnimCameraActor()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AnimCameraActor")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAnimCameraActor(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_AnimCameraActor(), "AnimCameraActor");
	}

	static int SetAnimCameraActor(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_AnimCameraActor(), "AnimCameraActor");
	}

	static PyObject* GetAutoPlaneShift(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->AutoPlaneShift);
	}

	static int SetAutoPlaneShift(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->AutoPlaneShift))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::AutoPlaneShift"), TEXT("value is not numeric"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CachedCameraShakeMod()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CachedCameraShakeMod")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCachedCameraShakeMod(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_CachedCameraShakeMod(), "CachedCameraShakeMod");
	}

	static int SetCachedCameraShakeMod(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_CachedCameraShakeMod(), "CachedCameraShakeMod");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CameraCachePrivate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CameraCachePrivate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCameraCachePrivate(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_CameraCachePrivate(), "CameraCachePrivate");
	}

	static int SetCameraCachePrivate(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_CameraCachePrivate(), "CameraCachePrivate");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CameraLensEffects()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CameraLensEffects")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCameraLensEffects(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_CameraLensEffects(), "CameraLensEffects");
	}

	static int SetCameraLensEffects(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_CameraLensEffects(), "CameraLensEffects");
	}

	static PyObject* GetDefaultAspectRatio(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->DefaultAspectRatio);
	}

	static int SetDefaultAspectRatio(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->DefaultAspectRatio))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::DefaultAspectRatio"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetDefaultFOV(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->DefaultFOV);
	}

	static int SetDefaultFOV(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->DefaultFOV))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::DefaultFOV"), TEXT("value is not numeric"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_DefaultModifiers()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("DefaultModifiers")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetDefaultModifiers(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperArrayFactory::Get().CreateInstance((void*)&InSelf->ValuePtr()->DefaultModifiers, CastField<FArrayProperty>(GetPropertyDef_DefaultModifiers().Prop), FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static PyObject* GetDefaultOrthoWidth(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->DefaultOrthoWidth);
	}

	static int SetDefaultOrthoWidth(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->DefaultOrthoWidth))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::DefaultOrthoWidth"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetFreeCamDistance(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->FreeCamDistance);
	}

	static int SetFreeCamDistance(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->FreeCamDistance))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::FreeCamDistance"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetFreeCamOffset(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector>::Get(), (void*)&InSelf->ValuePtr()->FreeCamOffset, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetFreeCamOffset(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->FreeCamOffset))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::FreeCamOffset"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_LastFrameCameraCachePrivate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("LastFrameCameraCachePrivate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetLastFrameCameraCachePrivate(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_LastFrameCameraCachePrivate(), "LastFrameCameraCachePrivate");
	}

	static int SetLastFrameCameraCachePrivate(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_LastFrameCameraCachePrivate(), "LastFrameCameraCachePrivate");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ModifierList()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ModifierList")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetModifierList(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_ModifierList(), "ModifierList");
	}

	static int SetModifierList(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_ModifierList(), "ModifierList");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_OnAudioFadeChangeEvent()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("OnAudioFadeChangeEvent")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetOnAudioFadeChangeEvent(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_OnAudioFadeChangeEvent(), "OnAudioFadeChangeEvent");
	}

	static int SetOnAudioFadeChangeEvent(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_OnAudioFadeChangeEvent(), "OnAudioFadeChangeEvent");
	}

	static PyObject* GetPCOwner(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->PCOwner);
	}

	static int SetPCOwner(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->PCOwner))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::PCOwner"), TEXT("value is not a compatible object"));
		return -1;
	}

	static PyObject* GetPendingViewTarget(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FTViewTarget>::Get(), (void*)&InSelf->ValuePtr()->PendingViewTarget, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetPendingViewTarget(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->PendingViewTarget))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::PendingViewTarget"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_PostProcessBlendCache()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("PostProcessBlendCache")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetPostProcessBlendCache(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_PostProcessBlendCache(), "PostProcessBlendCache");
	}

	static int SetPostProcessBlendCache(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_PostProcessBlendCache(), "PostProcessBlendCache");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ServerUpdateCameraTimeout()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ServerUpdateCameraTimeout")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetServerUpdateCameraTimeout(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_ServerUpdateCameraTimeout(), "ServerUpdateCameraTimeout");
	}

	static int SetServerUpdateCameraTimeout(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_ServerUpdateCameraTimeout(), "ServerUpdateCameraTimeout");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_TransformComponent()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = APlayerCameraManager::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("TransformComponent")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetTransformComponent(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_TransformComponent(), "TransformComponent");
	}

	static int SetTransformComponent(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_TransformComponent(), "TransformComponent");
	}

	static PyObject* GetViewPitchMax(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewPitchMax);
	}

	static int SetViewPitchMax(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewPitchMax))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewPitchMax"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetViewPitchMin(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewPitchMin);
	}

	static int SetViewPitchMin(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewPitchMin))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewPitchMin"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetViewRollMax(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewRollMax);
	}

	static int SetViewRollMax(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewRollMax))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewRollMax"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetViewRollMin(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewRollMin);
	}

	static int SetViewRollMin(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewRollMin))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewRollMin"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetViewTarget(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FTViewTarget>::Get(), (void*)&InSelf->ValuePtr()->ViewTarget, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetViewTarget(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->ViewTarget))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewTarget"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static PyObject* GetViewTargetOffset(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector>::Get(), (void*)&InSelf->ValuePtr()->ViewTargetOffset, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetViewTargetOffset(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->ViewTargetOffset))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewTargetOffset"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static PyObject* GetViewYawMax(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewYawMax);
	}

	static int SetViewYawMax(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewYawMax))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewYawMax"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetViewYawMin(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->ViewYawMin);
	}

	static int SetViewYawMin(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->ViewYawMin))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::ViewYawMin"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetbAutoCalculateOrthoPlanes(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bAutoCalculateOrthoPlanes);
	}

	static int SetbAutoCalculateOrthoPlanes(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bAutoCalculateOrthoPlanes = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bAutoCalculateOrthoPlanes"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbClientSimulatingViewTarget(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bClientSimulatingViewTarget);
	}

	static int SetbClientSimulatingViewTarget(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bClientSimulatingViewTarget = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bClientSimulatingViewTarget"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbDefaultConstrainAspectRatio(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bDefaultConstrainAspectRatio);
	}

	static int SetbDefaultConstrainAspectRatio(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bDefaultConstrainAspectRatio = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bDefaultConstrainAspectRatio"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbGameCameraCutThisFrame(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bGameCameraCutThisFrame);
	}

	static int SetbGameCameraCutThisFrame(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bGameCameraCutThisFrame = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bGameCameraCutThisFrame"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbIsOrthographic(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bIsOrthographic);
	}

	static int SetbIsOrthographic(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bIsOrthographic = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bIsOrthographic"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbUpdateOrthoPlanes(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bUpdateOrthoPlanes);
	}

	static int SetbUpdateOrthoPlanes(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bUpdateOrthoPlanes = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bUpdateOrthoPlanes"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbUseCameraHeightAsViewTarget(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bUseCameraHeightAsViewTarget);
	}

	static int SetbUseCameraHeightAsViewTarget(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bUseCameraHeightAsViewTarget = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bUseCameraHeightAsViewTarget"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbUseClientSideCameraUpdates(FUPyWrapperPlayerCameraManager* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bUseClientSideCameraUpdates);
	}

	static int SetbUseClientSideCameraUpdates(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bUseClientSideCameraUpdates = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("PlayerCameraManager::bUseClientSideCameraUpdates"), TEXT("value is not bool"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperPlayerCameraManagerGetSets[] = {
	{ UPyCStrCast("AnimCameraActor"), (getter)&FGetSets_PlayerCameraManager::GetAnimCameraActor, (setter)&FGetSets_PlayerCameraManager::SetAnimCameraActor, nullptr, nullptr },
	{ UPyCStrCast("AutoPlaneShift"), (getter)&FGetSets_PlayerCameraManager::GetAutoPlaneShift, (setter)&FGetSets_PlayerCameraManager::SetAutoPlaneShift, nullptr, nullptr },
	{ UPyCStrCast("CachedCameraShakeMod"), (getter)&FGetSets_PlayerCameraManager::GetCachedCameraShakeMod, (setter)&FGetSets_PlayerCameraManager::SetCachedCameraShakeMod, nullptr, nullptr },
	{ UPyCStrCast("CameraCachePrivate"), (getter)&FGetSets_PlayerCameraManager::GetCameraCachePrivate, (setter)&FGetSets_PlayerCameraManager::SetCameraCachePrivate, nullptr, nullptr },
	{ UPyCStrCast("CameraLensEffects"), (getter)&FGetSets_PlayerCameraManager::GetCameraLensEffects, (setter)&FGetSets_PlayerCameraManager::SetCameraLensEffects, nullptr, nullptr },
	{ UPyCStrCast("DefaultAspectRatio"), (getter)&FGetSets_PlayerCameraManager::GetDefaultAspectRatio, (setter)&FGetSets_PlayerCameraManager::SetDefaultAspectRatio, nullptr, nullptr },
	{ UPyCStrCast("DefaultFOV"), (getter)&FGetSets_PlayerCameraManager::GetDefaultFOV, (setter)&FGetSets_PlayerCameraManager::SetDefaultFOV, nullptr, nullptr },
	{ UPyCStrCast("DefaultModifiers"), (getter)&FGetSets_PlayerCameraManager::GetDefaultModifiers, nullptr, nullptr, nullptr },
	{ UPyCStrCast("DefaultOrthoWidth"), (getter)&FGetSets_PlayerCameraManager::GetDefaultOrthoWidth, (setter)&FGetSets_PlayerCameraManager::SetDefaultOrthoWidth, nullptr, nullptr },
	{ UPyCStrCast("FreeCamDistance"), (getter)&FGetSets_PlayerCameraManager::GetFreeCamDistance, (setter)&FGetSets_PlayerCameraManager::SetFreeCamDistance, nullptr, nullptr },
	{ UPyCStrCast("FreeCamOffset"), (getter)&FGetSets_PlayerCameraManager::GetFreeCamOffset, (setter)&FGetSets_PlayerCameraManager::SetFreeCamOffset, nullptr, nullptr },
	{ UPyCStrCast("LastFrameCameraCachePrivate"), (getter)&FGetSets_PlayerCameraManager::GetLastFrameCameraCachePrivate, (setter)&FGetSets_PlayerCameraManager::SetLastFrameCameraCachePrivate, nullptr, nullptr },
	{ UPyCStrCast("ModifierList"), (getter)&FGetSets_PlayerCameraManager::GetModifierList, (setter)&FGetSets_PlayerCameraManager::SetModifierList, nullptr, nullptr },
	{ UPyCStrCast("OnAudioFadeChangeEvent"), (getter)&FGetSets_PlayerCameraManager::GetOnAudioFadeChangeEvent, (setter)&FGetSets_PlayerCameraManager::SetOnAudioFadeChangeEvent, nullptr, nullptr },
	{ UPyCStrCast("PCOwner"), (getter)&FGetSets_PlayerCameraManager::GetPCOwner, (setter)&FGetSets_PlayerCameraManager::SetPCOwner, nullptr, nullptr },
	{ UPyCStrCast("PendingViewTarget"), (getter)&FGetSets_PlayerCameraManager::GetPendingViewTarget, (setter)&FGetSets_PlayerCameraManager::SetPendingViewTarget, nullptr, nullptr },
	{ UPyCStrCast("PostProcessBlendCache"), (getter)&FGetSets_PlayerCameraManager::GetPostProcessBlendCache, (setter)&FGetSets_PlayerCameraManager::SetPostProcessBlendCache, nullptr, nullptr },
	{ UPyCStrCast("ServerUpdateCameraTimeout"), (getter)&FGetSets_PlayerCameraManager::GetServerUpdateCameraTimeout, (setter)&FGetSets_PlayerCameraManager::SetServerUpdateCameraTimeout, nullptr, nullptr },
	{ UPyCStrCast("TransformComponent"), (getter)&FGetSets_PlayerCameraManager::GetTransformComponent, (setter)&FGetSets_PlayerCameraManager::SetTransformComponent, nullptr, nullptr },
	{ UPyCStrCast("ViewPitchMax"), (getter)&FGetSets_PlayerCameraManager::GetViewPitchMax, (setter)&FGetSets_PlayerCameraManager::SetViewPitchMax, nullptr, nullptr },
	{ UPyCStrCast("ViewPitchMin"), (getter)&FGetSets_PlayerCameraManager::GetViewPitchMin, (setter)&FGetSets_PlayerCameraManager::SetViewPitchMin, nullptr, nullptr },
	{ UPyCStrCast("ViewRollMax"), (getter)&FGetSets_PlayerCameraManager::GetViewRollMax, (setter)&FGetSets_PlayerCameraManager::SetViewRollMax, nullptr, nullptr },
	{ UPyCStrCast("ViewRollMin"), (getter)&FGetSets_PlayerCameraManager::GetViewRollMin, (setter)&FGetSets_PlayerCameraManager::SetViewRollMin, nullptr, nullptr },
	{ UPyCStrCast("ViewTarget"), (getter)&FGetSets_PlayerCameraManager::GetViewTarget, (setter)&FGetSets_PlayerCameraManager::SetViewTarget, nullptr, nullptr },
	{ UPyCStrCast("ViewTargetOffset"), (getter)&FGetSets_PlayerCameraManager::GetViewTargetOffset, (setter)&FGetSets_PlayerCameraManager::SetViewTargetOffset, nullptr, nullptr },
	{ UPyCStrCast("ViewYawMax"), (getter)&FGetSets_PlayerCameraManager::GetViewYawMax, (setter)&FGetSets_PlayerCameraManager::SetViewYawMax, nullptr, nullptr },
	{ UPyCStrCast("ViewYawMin"), (getter)&FGetSets_PlayerCameraManager::GetViewYawMin, (setter)&FGetSets_PlayerCameraManager::SetViewYawMin, nullptr, nullptr },
	{ UPyCStrCast("bAutoCalculateOrthoPlanes"), (getter)&FGetSets_PlayerCameraManager::GetbAutoCalculateOrthoPlanes, (setter)&FGetSets_PlayerCameraManager::SetbAutoCalculateOrthoPlanes, nullptr, nullptr },
	{ UPyCStrCast("bClientSimulatingViewTarget"), (getter)&FGetSets_PlayerCameraManager::GetbClientSimulatingViewTarget, (setter)&FGetSets_PlayerCameraManager::SetbClientSimulatingViewTarget, nullptr, nullptr },
	{ UPyCStrCast("bDefaultConstrainAspectRatio"), (getter)&FGetSets_PlayerCameraManager::GetbDefaultConstrainAspectRatio, (setter)&FGetSets_PlayerCameraManager::SetbDefaultConstrainAspectRatio, nullptr, nullptr },
	{ UPyCStrCast("bGameCameraCutThisFrame"), (getter)&FGetSets_PlayerCameraManager::GetbGameCameraCutThisFrame, (setter)&FGetSets_PlayerCameraManager::SetbGameCameraCutThisFrame, nullptr, nullptr },
	{ UPyCStrCast("bIsOrthographic"), (getter)&FGetSets_PlayerCameraManager::GetbIsOrthographic, (setter)&FGetSets_PlayerCameraManager::SetbIsOrthographic, nullptr, nullptr },
	{ UPyCStrCast("bUpdateOrthoPlanes"), (getter)&FGetSets_PlayerCameraManager::GetbUpdateOrthoPlanes, (setter)&FGetSets_PlayerCameraManager::SetbUpdateOrthoPlanes, nullptr, nullptr },
	{ UPyCStrCast("bUseCameraHeightAsViewTarget"), (getter)&FGetSets_PlayerCameraManager::GetbUseCameraHeightAsViewTarget, (setter)&FGetSets_PlayerCameraManager::SetbUseCameraHeightAsViewTarget, nullptr, nullptr },
	{ UPyCStrCast("bUseClientSideCameraUpdates"), (getter)&FGetSets_PlayerCameraManager::GetbUseClientSideCameraUpdates, (setter)&FGetSets_PlayerCameraManager::SetbUseClientSideCameraUpdates, nullptr, nullptr },
	{ nullptr }
};



struct FMethods_PlayerCameraManager
{
	static PyObject* CallAddGenericCameraLensEffect(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(InArg, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::AddGenericCameraLensEffect"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->AddGenericCameraLensEffect(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallAddNewCameraModifier(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(InArg, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::AddNewCameraModifier"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->AddNewCameraModifier(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallBlueprintUpdateCamera(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		AActor* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::BlueprintUpdateCamera"), TEXT("invalid argument"));
			return nullptr;
		}

		FVector OutParam0;
		FRotator OutParam1;
		float OutParam2 = 0.0f;
		// Call the method
		const bool ReturnValue = InSelf->ValuePtr()->BlueprintUpdateCamera(Arg0, OutParam0, OutParam1, OutParam2);

		// Build return tuple with 4 values
		PyObject* ReturnTuple = PyTuple_New(4);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, PyBool_FromLong(ReturnValue ? 1 : 0));
		// Add output parameter 'NewCameraLocation' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(OutParam0));
		// Add output parameter 'NewCameraRotation' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 2, UPyConversion::PythonizeStructInstance(OutParam1));
		// Add output parameter 'NewCameraFOV' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 3, UPyConversion::Pythonize(OutParam2));

		return ReturnTuple;
	}

	static PyObject* CallClearCameraLensEffects(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->ClearCameraLensEffects();
		Py_RETURN_NONE;
	}

	static PyObject* CallFindCameraModifierByClass(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(InArg, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::FindCameraModifierByClass"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->FindCameraModifierByClass(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetCameraLocation(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetCameraLocation();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetCameraRotation(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetCameraRotation();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetFOVAngle(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetFOVAngle();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetOwningPlayerController(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetOwningPlayerController();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallOnPhotographyMultiPartCaptureEnd(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->OnPhotographyMultiPartCaptureEnd();
		Py_RETURN_NONE;
	}

	static PyObject* CallOnPhotographyMultiPartCaptureStart(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->OnPhotographyMultiPartCaptureStart();
		Py_RETURN_NONE;
	}

	static PyObject* CallOnPhotographySessionEnd(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->OnPhotographySessionEnd();
		Py_RETURN_NONE;
	}

	static PyObject* CallOnPhotographySessionStart(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->OnPhotographySessionStart();
		Py_RETURN_NONE;
	}

	static PyObject* CallPhotographyCameraModify(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FVector Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::PhotographyCameraModify"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::PhotographyCameraModify"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FVector Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::PhotographyCameraModify"), TEXT("invalid argument"));
			return nullptr;
		}

		FVector OutParam0;
		InSelf->ValuePtr()->PhotographyCameraModify(Arg0, Arg1, Arg2, OutParam0);
		return UPyConversion::PythonizeStructInstance(OutParam0);
	}

	static PyObject* CallRemoveCameraModifier(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		UCameraModifier* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::RemoveCameraModifier"), TEXT("invalid argument"));
			return nullptr;
		}

		const bool bResult = InSelf->ValuePtr()->RemoveCameraModifier(Arg0);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallRemoveGenericCameraLensEffect(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InArg))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("PlayerCameraManager::RemoveGenericCameraLensEffect"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallSetGameCameraCutThisFrame(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->SetGameCameraCutThisFrame();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetManualCameraFade(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::SetManualCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FLinearColor Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::SetManualCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		bool Arg2 = false;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::SetManualCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetManualCameraFade(Arg0, Arg1, Arg2);
		Py_RETURN_NONE;
	}

	static PyObject* CallStartCameraFade(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		float Arg1 = 0.0f;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		float Arg2 = 0.0f;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		FLinearColor Arg3;
		if (!UPyConversion::NativizeStructInstance(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = (ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		bool Arg4 = false;
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg5 = (PyArg4 && ArgCount > 5) ? PyTuple_GetItem(InArgs, 5) : nullptr;
		bool Arg5 = false;
		if (PyArg5 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg5, Arg5))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraFade"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StartCameraFade(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5);
		Py_RETURN_NONE;
	}

	static PyObject* CallStartCameraShake(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg0, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShake"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		float Arg1 = 1.000000;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShake"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg2 = (PyArg1 && ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		ECameraShakePlaySpace Arg2 = ECameraShakePlaySpace::CameraLocal;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::NativizeEnumEntry(PyArg2, StaticEnum<ECameraShakePlaySpace>(), Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShake"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		FRotator Arg3;
		if (!UPyConversion::NativizeStructInstance(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShake"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->StartCameraShake(Arg0, Arg1, Arg2, Arg3);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallStartCameraShakeFromSource(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg0, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShakeFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UCameraShakeSourceComponent* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShakeFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = (ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		float Arg2 = 1.000000;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShakeFromSource"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg3 = (PyArg2 && ArgCount > 3) ? PyTuple_GetItem(InArgs, 3) : nullptr;
		ECameraShakePlaySpace Arg3 = ECameraShakePlaySpace::CameraLocal;
		if (PyArg3 != nullptr)
		{
			if (!UPyConversion::NativizeEnumEntry(PyArg3, StaticEnum<ECameraShakePlaySpace>(), Arg3))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShakeFromSource"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg4 = PyTuple_GetItem(InArgs, 4);
		if (PyArg4 == nullptr)
		{
			return nullptr;
		}
		FRotator Arg4;
		if (!UPyConversion::NativizeStructInstance(PyArg4, Arg4))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StartCameraShakeFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->StartCameraShakeFromSource(Arg0, Arg1, Arg2, Arg3, Arg4);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallStopAllCameraShakes(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = (ArgCount > 0) ? PyTuple_GetItem(InArgs, 0) : nullptr;
		bool Arg0 = true;
		if (PyArg0 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg0, Arg0))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllCameraShakes"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StopAllCameraShakes(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallStopAllCameraShakesFromSource(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UCameraShakeSourceComponent* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllCameraShakesFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		bool Arg1 = true;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllCameraShakesFromSource"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StopAllCameraShakesFromSource(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallStopAllInstancesOfCameraShake(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg0, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllInstancesOfCameraShake"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		bool Arg1 = true;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllInstancesOfCameraShake"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StopAllInstancesOfCameraShake(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallStopAllInstancesOfCameraShakeFromSource(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg0, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllInstancesOfCameraShakeFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UCameraShakeSourceComponent* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllInstancesOfCameraShakeFromSource"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = (ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		bool Arg2 = true;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopAllInstancesOfCameraShakeFromSource"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StopAllInstancesOfCameraShakeFromSource(Arg0, Arg1, Arg2);
		Py_RETURN_NONE;
	}

	static PyObject* CallStopCameraFade(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->StopCameraFade();
		Py_RETURN_NONE;
	}

	static PyObject* CallStopCameraShake(FUPyWrapperPlayerCameraManager* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UCameraShakeBase* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopCameraShake"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		bool Arg1 = true;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("PlayerCameraManager::StopCameraShake"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		InSelf->ValuePtr()->StopCameraShake(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSwapPendingViewTargetWhenUsingClientSideCameraUpdates(FUPyWrapperPlayerCameraManager* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		static UFunction* Func = APlayerCameraManager::StaticClass()->FindFunctionByName(TEXT("SwapPendingViewTargetWhenUsingClientSideCameraUpdates"));
		if (Func)
		{
			uint8* Parms = (uint8*)FMemory::Malloc(Func->ParmsSize);
			FMemory::Memzero(Parms, Func->ParmsSize);
			InSelf->ValuePtr()->ProcessEvent(Func, Parms);
			FMemory::Free(Parms);
		}
		Py_RETURN_NONE;
	}

};


static PyMethodDef FUPyWrapperPlayerCameraManagerPyMethodDefs[] = {
	{ "AddGenericCameraLensEffect", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallAddGenericCameraLensEffect), METH_O, nullptr },
	{ "AddNewCameraModifier", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallAddNewCameraModifier), METH_O, nullptr },
	{ "BlueprintUpdateCamera", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallBlueprintUpdateCamera), METH_O, nullptr },
	{ "ClearCameraLensEffects", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallClearCameraLensEffects), METH_NOARGS, nullptr },
	{ "FindCameraModifierByClass", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallFindCameraModifierByClass), METH_O, nullptr },
	{ "GetCameraLocation", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallGetCameraLocation), METH_NOARGS, nullptr },
	{ "GetCameraRotation", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallGetCameraRotation), METH_NOARGS, nullptr },
	{ "GetFOVAngle", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallGetFOVAngle), METH_NOARGS, nullptr },
	{ "GetOwningPlayerController", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallGetOwningPlayerController), METH_NOARGS, nullptr },
	{ "OnPhotographyMultiPartCaptureEnd", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallOnPhotographyMultiPartCaptureEnd), METH_NOARGS, nullptr },
	{ "OnPhotographyMultiPartCaptureStart", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallOnPhotographyMultiPartCaptureStart), METH_NOARGS, nullptr },
	{ "OnPhotographySessionEnd", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallOnPhotographySessionEnd), METH_NOARGS, nullptr },
	{ "OnPhotographySessionStart", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallOnPhotographySessionStart), METH_NOARGS, nullptr },
	{ "PhotographyCameraModify", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallPhotographyCameraModify), METH_VARARGS, nullptr },
	{ "RemoveCameraModifier", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallRemoveCameraModifier), METH_O, nullptr },
	{ "RemoveGenericCameraLensEffect", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallRemoveGenericCameraLensEffect), METH_O, nullptr },
	{ "SetGameCameraCutThisFrame", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallSetGameCameraCutThisFrame), METH_NOARGS, nullptr },
	{ "SetManualCameraFade", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallSetManualCameraFade), METH_VARARGS, nullptr },
	{ "StartCameraFade", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStartCameraFade), METH_VARARGS, nullptr },
	{ "StartCameraShake", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStartCameraShake), METH_VARARGS, nullptr },
	{ "StartCameraShakeFromSource", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStartCameraShakeFromSource), METH_VARARGS, nullptr },
	{ "StopAllCameraShakes", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopAllCameraShakes), METH_VARARGS, nullptr },
	{ "StopAllCameraShakesFromSource", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopAllCameraShakesFromSource), METH_VARARGS, nullptr },
	{ "StopAllInstancesOfCameraShake", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopAllInstancesOfCameraShake), METH_VARARGS, nullptr },
	{ "StopAllInstancesOfCameraShakeFromSource", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopAllInstancesOfCameraShakeFromSource), METH_VARARGS, nullptr },
	{ "StopCameraFade", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopCameraFade), METH_NOARGS, nullptr },
	{ "StopCameraShake", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallStopCameraShake), METH_VARARGS, nullptr },
	{ "SwapPendingViewTargetWhenUsingClientSideCameraUpdates", UPyCFunctionCast(&FMethods_PlayerCameraManager::CallSwapPendingViewTargetWhenUsingClientSideCameraUpdates), METH_NOARGS, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperPlayerCameraManager(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperPlayerCameraManagerType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperPlayerCameraManagerPyMethodDefs;
	PyType->tp_getset = FUPyWrapperPlayerCameraManagerGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperPlayerCameraManager(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(APlayerCameraManager::StaticClass(), DoInitWrapperPlayerCameraManager);
}

FUPyWrapperPlayerCameraManager* UPyIsPlayerCameraManager(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperPlayerCameraManagerType))
	{
		return (FUPyWrapperPlayerCameraManager*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, APlayerCameraManager*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperPlayerCameraManager* PyPlayerCameraManager = UPyIsPlayerCameraManager(PyObj))
		{
			if (!FUPyWrapperObjectBase::ValidateInternalState(PyPlayerCameraManager))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyPlayerCameraManager->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'APlayerCameraManager'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
