
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "GameFramework/Character.h"


/** Python type for FUPyWrapperCharacter */
extern PyTypeObject UPyWrapperCharacterType;

/** Initialize the UPyWrapperCharacterType types and add them to the given Python module */
void InitializeUPyWrapperCharacter(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperCharacter: public FUPyWrapperObjectBase 
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperCharacterType;
	}

	UNREALPYTHON_API ACharacter* ValuePtr() const
	{
		return Cast<ACharacter>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperCharacter* UPyIsCharacter(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, ACharacter*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
