
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Camera/CameraComponent.h"


/** Python type for FUPyWrapperCameraComponent */
extern PyTypeObject UPyWrapperCameraComponentType;

/** Initialize the UPyWrapperCameraComponentType types and add them to the given Python module */
void InitializeUPyWrapperCameraComponent(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperCameraComponent: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperCameraComponentType;
	}

	UNREALPYTHON_API UCameraComponent* ValuePtr() const
	{
		return Cast<UCameraComponent>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperCameraComponent* UPyIsCameraComponent(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UCameraComponent*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
