
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "Engine/HitResult.h"


/** Python type for FUPyWrapperHitResult */
extern PyTypeObject UPyWrapperHitResultType;

/** Initialize the UPyWrapperHitResultType types and add them to the given Python module */
void InitializeUPyWrapperHitResult(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperHitResult: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperHitResultType;
	}

	UNREALPYTHON_API FHitResult* ValuePtr() const
	{
		return static_cast<FHitResult*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FHitResult& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperHitResult* UPyIsHitResult(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FHitResult& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FHitResult& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
