
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Engine/Struct/UPyWrapperTimerHandle.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperTimerHandleType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"TimerHandle", /* tp_name */
	sizeof(FUPyWrapperTimerHandle), /* tp_basicsize */
};

struct FGetSets_TimerHandle
{
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_Handle()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UScriptStruct* ScriptStruct = TBaseStructure<FTimerHandle>::Get())
			{
				if (const FProperty* FoundProperty = ScriptStruct->FindPropertyByName(TEXT("Handle")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetHandle(FUPyWrapperTimerHandle* InSelf, void* InClosure)
	{
		if (!FUPyWrapperTimerHandle::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperStruct::GetPropertyValue(InSelf, GetPropertyDef_Handle(), "Handle");
	}

	static int SetHandle(FUPyWrapperTimerHandle* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperTimerHandle::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperStruct::SetPropertyValue(InSelf, InValue, GetPropertyDef_Handle(), "Handle");
	}

};


static PyGetSetDef FUPyWrapperTimerHandleGetSets[] = {
	{ UPyCStrCast("Handle"), (getter)&FGetSets_TimerHandle::GetHandle, (setter)&FGetSets_TimerHandle::SetHandle, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_TimerHandle
{
	static int Init(FUPyWrapperTimerHandle* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		return FUPyWrapperStruct::Init(InSelf);
	}
};





PyTypeObject* DoInitWrapperTimerHandle(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperTimerHandleType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_TimerHandle::Init;
	PyType->tp_getset = FUPyWrapperTimerHandleGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperTimerHandle(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FTimerHandle>::Get(), DoInitWrapperTimerHandle);
}

PyObject* FUPyWrapperTimerHandle::CreateInstance(const FTimerHandle& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperTimerHandleType, TBaseStructure<FTimerHandle>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperTimerHandle* UPyIsTimerHandle(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperTimerHandleType))
	{
		return (FUPyWrapperTimerHandle*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FTimerHandle& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperTimerHandle* PyVector = UPyIsTimerHandle(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FTimerHandle'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}

	FUPyConversionResult PythonizeStructInstance(const FTimerHandle& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperTimerHandle::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
