
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperBox */
extern PyTypeObject UPyWrapperBoxType;

/** Initialize the UPyWrapperBoxType types and add them to the given Python module */
void InitializeUPyWrapperBox(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperBox: public TUPyWrapperInlineStruct<FBox>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperBoxType;
	}

	UNREALPYTHON_API FBox* ValuePtr() const
	{
		return static_cast<FBox*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FBox& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperBox* UPyIsBox(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FBox& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FBox& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
