
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperBoxSphereBounds */
extern PyTypeObject UPyWrapperBoxSphereBoundsType;

/** Initialize the UPyWrapperBoxSphereBoundsType types and add them to the given Python module */
void InitializeUPyWrapperBoxSphereBounds(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperBoxSphereBounds: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperBoxSphereBoundsType;
	}

	UNREALPYTHON_API FBoxSphereBounds* ValuePtr() const
	{
		return static_cast<FBoxSphereBounds*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FBoxSphereBounds& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperBoxSphereBounds* UPyIsBoxSphereBounds(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FBoxSphereBounds& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FBoxSphereBounds& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
