
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/CoreUObject/Struct/UPyWrapperBoxSphereBounds.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperBoxSphereBoundsType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"BoxSphereBounds", /* tp_name */
	sizeof(FUPyWrapperBoxSphereBounds), /* tp_basicsize */
};

struct FGetSets_BoxSphereBounds
{
	static PyObject* GetBoxExtent(FUPyWrapperBoxSphereBounds* InSelf, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector>::Get(), (void*)&InSelf->ValuePtr()->BoxExtent, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetBoxExtent(FUPyWrapperBoxSphereBounds* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->BoxExtent))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("BoxSphereBounds::BoxExtent"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static PyObject* GetOrigin(FUPyWrapperBoxSphereBounds* InSelf, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector>::Get(), (void*)&InSelf->ValuePtr()->Origin, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetOrigin(FUPyWrapperBoxSphereBounds* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->Origin))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("BoxSphereBounds::Origin"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static PyObject* GetSphereRadius(FUPyWrapperBoxSphereBounds* InSelf, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->SphereRadius);
	}

	static int SetSphereRadius(FUPyWrapperBoxSphereBounds* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperBoxSphereBounds::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->SphereRadius))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("BoxSphereBounds::SphereRadius"), TEXT("value is not numeric"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperBoxSphereBoundsGetSets[] = {
	{ UPyCStrCast("BoxExtent"), (getter)&FGetSets_BoxSphereBounds::GetBoxExtent, (setter)&FGetSets_BoxSphereBounds::SetBoxExtent, nullptr, nullptr },
	{ UPyCStrCast("Origin"), (getter)&FGetSets_BoxSphereBounds::GetOrigin, (setter)&FGetSets_BoxSphereBounds::SetOrigin, nullptr, nullptr },
	{ UPyCStrCast("SphereRadius"), (getter)&FGetSets_BoxSphereBounds::GetSphereRadius, (setter)&FGetSets_BoxSphereBounds::SetSphereRadius, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_BoxSphereBounds
{
	static int Init(FUPyWrapperBoxSphereBounds* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		return FUPyWrapperStruct::Init(InSelf);
	}
};





PyTypeObject* DoInitWrapperBoxSphereBounds(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperBoxSphereBoundsType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_BoxSphereBounds::Init;
	PyType->tp_getset = FUPyWrapperBoxSphereBoundsGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperBoxSphereBounds(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FBoxSphereBounds>::Get(), DoInitWrapperBoxSphereBounds);
}

PyObject* FUPyWrapperBoxSphereBounds::CreateInstance(const FBoxSphereBounds& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperBoxSphereBoundsType, TBaseStructure<FBoxSphereBounds>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperBoxSphereBounds* UPyIsBoxSphereBounds(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperBoxSphereBoundsType))
	{
		return (FUPyWrapperBoxSphereBounds*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FBoxSphereBounds& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperBoxSphereBounds* PyVector = UPyIsBoxSphereBounds(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FBoxSphereBounds'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}

	FUPyConversionResult PythonizeStructInstance(const FBoxSphereBounds& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperBoxSphereBounds::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
