
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperIntVector */
extern PyTypeObject UPyWrapperIntVectorType;

/** Initialize the UPyWrapperIntVectorType types and add them to the given Python module */
void InitializeUPyWrapperIntVector(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperIntVector: public TUPyWrapperInlineStruct<FIntVector>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperIntVectorType;
	}

	UNREALPYTHON_API FIntVector* ValuePtr() const
	{
		return static_cast<FIntVector*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FIntVector& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperIntVector* UPyIsIntVector(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FIntVector& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FIntVector& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
