
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/CoreUObject/Struct/UPyWrapperRotator.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"
#include "DynamicTypes/UPyConstant.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperRotatorType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Rotator", /* tp_name */
	sizeof(FUPyWrapperRotator), /* tp_basicsize */
};

struct FGetSets_Rotator
{
	static PyObject* GetPitch(FUPyWrapperRotator* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->Pitch);
	}

	static int SetPitch(FUPyWrapperRotator* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->Pitch))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Rotator::Pitch"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetRoll(FUPyWrapperRotator* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->Roll);
	}

	static int SetRoll(FUPyWrapperRotator* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->Roll))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Rotator::Roll"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetYaw(FUPyWrapperRotator* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->Yaw);
	}

	static int SetYaw(FUPyWrapperRotator* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->Yaw))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Rotator::Yaw"), TEXT("value is not numeric"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperRotatorGetSets[] = {
	{ UPyCStrCast("Pitch"), (getter)&FGetSets_Rotator::GetPitch, (setter)&FGetSets_Rotator::SetPitch, nullptr, nullptr },
	{ UPyCStrCast("Roll"), (getter)&FGetSets_Rotator::GetRoll, (setter)&FGetSets_Rotator::SetRoll, nullptr, nullptr },
	{ UPyCStrCast("Yaw"), (getter)&FGetSets_Rotator::GetYaw, (setter)&FGetSets_Rotator::SetYaw, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_Rotator
{
	static int Rotator_Init_ArgCnt0_Overload0(FUPyWrapperRotator* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		new (InSelf->StructInstance) FRotator();
		return 0;
	}


	static int Rotator_Init_ArgCnt1_Overload0(FUPyWrapperRotator* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		double Arg0 = 0.0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			return -1;
		}

		new (InSelf->StructInstance) FRotator(Arg0);
		return 0;
	}


	static int Rotator_Init_ArgCnt3_Overload0(FUPyWrapperRotator* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		double Arg0 = 0.0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			return -1;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return -1;
		}
		double Arg1 = 0.0;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			return -1;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return -1;
		}
		double Arg2 = 0.0;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			return -1;
		}

		new (InSelf->StructInstance) FRotator(Arg0, Arg1, Arg2);
		return 0;
	}


	static int Init(FUPyWrapperRotator* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		const int BaseInit = FUPyWrapperStruct::Init(InSelf);
		if (BaseInit != 0)
		{
			return BaseInit;
		}

		switch (PyTuple_Size(InArgs))
		{
		case 0:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Rotator::Rotator_Init_ArgCnt0_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		case 1:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Rotator::Rotator_Init_ArgCnt1_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		case 3:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Rotator::Rotator_Init_ArgCnt3_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		default:
			break;
		}

		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__init__"), TEXT("invalid argument"));
		return -1;
	}

	static int Rotator___eq___CmpAttempt0(FUPyWrapperRotator* InSelf, PyObject* InOther)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) == Arg0;
		return bResult ? 1 : 0;
	}

	static int Rotator___ne___CmpAttempt0(FUPyWrapperRotator* InSelf, PyObject* InOther)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) != Arg0;
		return bResult ? 1 : 0;
	}

	static PyObject* RichCmp(FUPyWrapperRotator* InSelf, PyObject* InOther, int InOp)
	{
		bool bHandled = false;
		bool bResult = false;
		switch (InOp)
		{
		case Py_EQ:
		{
			if (!bHandled)
			{
				int AttemptResult = Rotator___eq___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
				else
				{
					PyErr_Clear();
				}
			}
			break;
		}
		case Py_NE:
		{
			if (!bHandled)
			{
				int AttemptResult = Rotator___ne___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
				else
				{
					PyErr_Clear();
				}
			}
			break;
		}
		default:
			break;
		}
		if (!bHandled)
		{
			Py_RETURN_NOTIMPLEMENTED;
		}
		if (bResult)
		{
			Py_RETURN_TRUE;
		}
		Py_RETURN_FALSE;
	}
};

struct FNumberFuncs_Rotator
{
	static PyObject* Op_add_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InRHS, Arg0))
		{
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->operator+(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* Op_add(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_add_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__add__"), TEXT("operator not supported"));
		return nullptr;
	}

	static PyObject* Op_iadd_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InRHS, Arg0))
		{
			return nullptr;
		}

		InSelf->ValuePtr()->operator+=(Arg0);
		Py_INCREF(InSelf);
		return (PyObject*)InSelf;
	}

	static PyObject* Op_iadd(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_iadd_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__iadd__"), TEXT("operator not supported"));
		return nullptr;
	}

	static PyObject* Op_imul_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		double Arg0 = 0.0;
		if (!UPyConversion::Nativize(InRHS, Arg0))
		{
			return nullptr;
		}

		InSelf->ValuePtr()->operator*=(Arg0);
		Py_INCREF(InSelf);
		return (PyObject*)InSelf;
	}

	static PyObject* Op_imul(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_imul_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__imul__"), TEXT("operator not supported"));
		return nullptr;
	}

	static PyObject* Op_isub_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InRHS, Arg0))
		{
			return nullptr;
		}

		InSelf->ValuePtr()->operator-=(Arg0);
		Py_INCREF(InSelf);
		return (PyObject*)InSelf;
	}

	static PyObject* Op_isub(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_isub_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__isub__"), TEXT("operator not supported"));
		return nullptr;
	}

	static PyObject* Op_mul_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		double Arg0 = 0.0;
		if (!UPyConversion::Nativize(InRHS, Arg0))
		{
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->operator*(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* Op_mul(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_mul_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__mul__"), TEXT("operator not supported"));
		return nullptr;
	}

	static PyObject* Op_sub_Attempt0(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		FRotator Arg0;
		if (!UPyConversion::NativizeStructInstance(InRHS, Arg0))
		{
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->operator-(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* Op_sub(FUPyWrapperRotator* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_sub_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::__sub__"), TEXT("operator not supported"));
		return nullptr;
	}

};

struct FMethods_Rotator
{
	static PyObject* CallClamp(FUPyWrapperRotator* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->Clamp();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetInverse(FUPyWrapperRotator* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetInverse();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetNormalized(FUPyWrapperRotator* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetNormalized();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallIsNearlyZero(FUPyWrapperRotator* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = (ArgCount > 0) ? PyTuple_GetItem(InArgs, 0) : nullptr;
		double Arg0 = 0.000100;
		if (PyArg0 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg0, Arg0))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::IsNearlyZero"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		const bool bResult = InSelf->ValuePtr()->IsNearlyZero(Arg0);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallIsZero(FUPyWrapperRotator* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsZero();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallRotateVector(FUPyWrapperRotator* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::RotateVector"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->RotateVector(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallUnrotateVector(FUPyWrapperRotator* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Rotator::UnrotateVector"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->UnrotateVector(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallVector(FUPyWrapperRotator* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->Vector();
		return UPyConversion::PythonizeStructInstance(Result);
	}

};


static PyMethodDef FUPyWrapperRotatorPyMethodDefs[] = {
	{ "Clamp", UPyCFunctionCast(&FMethods_Rotator::CallClamp), METH_NOARGS, nullptr },
	{ "GetInverse", UPyCFunctionCast(&FMethods_Rotator::CallGetInverse), METH_NOARGS, nullptr },
	{ "GetNormalized", UPyCFunctionCast(&FMethods_Rotator::CallGetNormalized), METH_NOARGS, nullptr },
	{ "IsNearlyZero", UPyCFunctionCast(&FMethods_Rotator::CallIsNearlyZero), METH_VARARGS, nullptr },
	{ "IsZero", UPyCFunctionCast(&FMethods_Rotator::CallIsZero), METH_NOARGS, nullptr },
	{ "RotateVector", UPyCFunctionCast(&FMethods_Rotator::CallRotateVector), METH_O, nullptr },
	{ "UnrotateVector", UPyCFunctionCast(&FMethods_Rotator::CallUnrotateVector), METH_O, nullptr },
	{ "Vector", UPyCFunctionCast(&FMethods_Rotator::CallVector), METH_NOARGS, nullptr },
	{ nullptr }
};

struct FConstants_Rotator
{
	static PyObject* GetConstant_ZeroRotator(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FRotator::ZeroRotator;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static FUPyConstantDef* Table()
	{
		static FUPyConstantDef Constants[] = {
		{ nullptr, (PyConstantGetter)&FConstants_Rotator::GetConstant_ZeroRotator, UPyCStrCast("ZeroRotator"), nullptr },
			{ nullptr, nullptr, nullptr, nullptr }
		};
		return Constants;
	}
};


PyTypeObject* DoInitWrapperRotator(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperRotatorType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_Rotator::Init;
	PyType->tp_methods = FUPyWrapperRotatorPyMethodDefs;
	PyType->tp_getset = FUPyWrapperRotatorGetSets;
	PyType->tp_richcompare = (richcmpfunc)&FFuncs_Rotator::RichCmp;
	static PyNumberMethods PyNumber;
	PyNumber.nb_add = (binaryfunc)&FNumberFuncs_Rotator::Op_add;
	PyNumber.nb_inplace_add = (binaryfunc)&FNumberFuncs_Rotator::Op_iadd;
	PyNumber.nb_inplace_multiply = (binaryfunc)&FNumberFuncs_Rotator::Op_imul;
	PyNumber.nb_inplace_subtract = (binaryfunc)&FNumberFuncs_Rotator::Op_isub;
	PyNumber.nb_multiply = (binaryfunc)&FNumberFuncs_Rotator::Op_mul;
	PyNumber.nb_subtract = (binaryfunc)&FNumberFuncs_Rotator::Op_sub;
	PyType->tp_as_number = &PyNumber;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyConstantDef::AddConstantsToType(FConstants_Rotator::Table(), PyType);
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperRotator(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterInlineStructFactory(StaticCastSharedRef<const IUPyWrapperInlineStructFactory>(MakeShared<TUPyWrapperInlineStructFactory<FRotator>>()));
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FRotator>::Get(), DoInitWrapperRotator);
}

PyObject* FUPyWrapperRotator::CreateInstance(const FRotator& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperRotatorType, TBaseStructure<FRotator>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperRotator* UPyIsRotator(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperRotatorType))
	{
		return (FUPyWrapperRotator*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FRotator& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperRotator* PyVector = UPyIsRotator(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FRotator'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
	
	FUPyConversionResult PythonizeStructInstance(const FRotator& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperRotator::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
