// Copyright Epic Games, Inc. All Rights Reserved.

// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperQuat */
extern PyTypeObject UPyWrapperQuatType;

/** Initialize the UPyWrapperQuatType types and add them to the given Python module */
void InitializeUPyWrapperQuat(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperQuat: public TUPyWrapperInlineStruct<FQuat>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperQuatType;
	}

	UNREALPYTHON_API FQuat* ValuePtr() const
	{
		return static_cast<FQuat*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FQuat& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperQuat* UPyIsQuat(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FQuat& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FQuat& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
