
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperVector2D */
extern PyTypeObject UPyWrapperVector2DType;

/** Initialize the UPyWrapperVector2DType types and add them to the given Python module */
void InitializeUPyWrapperVector2D(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperVector2D: public TUPyWrapperInlineStruct<FVector2D>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperVector2DType;
	}

	UNREALPYTHON_API FVector2D* ValuePtr() const
	{
		return static_cast<FVector2D*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FVector2D& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperVector2D* UPyIsVector2D(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FVector2D& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FVector2D& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
