// Copyright Epic Games, Inc. All Rights Reserved.

// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/SoftObjectPath.h"


/** Python type for FUPyWrapperSoftClassPath */
extern PyTypeObject UPyWrapperSoftClassPathType;

/** Initialize the UPyWrapperSoftClassPathType types and add them to the given Python module */
void InitializeUPyWrapperSoftClassPath(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperSoftClassPath: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperSoftClassPathType;
	}

	UNREALPYTHON_API FSoftClassPath* ValuePtr() const
	{
		return static_cast<FSoftClassPath*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FSoftClassPath& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperSoftClassPath* UPyIsSoftClassPath(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FSoftClassPath& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FSoftClassPath& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
