
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "UObject/NoExportTypes.h"


/** Python type for FUPyWrapperGuid */
extern PyTypeObject UPyWrapperGuidType;

/** Initialize the UPyWrapperGuidType types and add them to the given Python module */
void InitializeUPyWrapperGuid(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperGuid: public TUPyWrapperInlineStruct<FGuid>
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperGuidType;
	}

	UNREALPYTHON_API FGuid* ValuePtr() const
	{
		return static_cast<FGuid*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FGuid& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperGuid* UPyIsGuid(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FGuid& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FGuid& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
