// Copyright Epic Games, Inc. All Rights Reserved.

// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/CoreUObject/Struct/UPyWrapperColor.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"
#include "DynamicTypes/UPyConstant.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperColorType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Color", /* tp_name */
	sizeof(FUPyWrapperColor), /* tp_basicsize */
};

struct FGetSets_Color
{
	static PyObject* GetA(FUPyWrapperColor* InSelf, void* InClosure)
	{
		return UPyConversion::Pythonize(InSelf->ValuePtr()->A);
	}

	static int SetA(FUPyWrapperColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->A))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Color::A"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetB(FUPyWrapperColor* InSelf, void* InClosure)
	{
		return UPyConversion::Pythonize(InSelf->ValuePtr()->B);
	}

	static int SetB(FUPyWrapperColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->B))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Color::B"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetG(FUPyWrapperColor* InSelf, void* InClosure)
	{
		return UPyConversion::Pythonize(InSelf->ValuePtr()->G);
	}

	static int SetG(FUPyWrapperColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->G))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Color::G"), TEXT("value is not numeric"));
		return -1;
	}

	static PyObject* GetR(FUPyWrapperColor* InSelf, void* InClosure)
	{
		return UPyConversion::Pythonize(InSelf->ValuePtr()->R);
	}

	static int SetR(FUPyWrapperColor* InSelf, PyObject* InValue, void* InClosure)
	{
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->R))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Color::R"), TEXT("value is not numeric"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperColorGetSets[] = {
	{ UPyCStrCast("A"), (getter)&FGetSets_Color::GetA, (setter)&FGetSets_Color::SetA, nullptr, nullptr },
	{ UPyCStrCast("B"), (getter)&FGetSets_Color::GetB, (setter)&FGetSets_Color::SetB, nullptr, nullptr },
	{ UPyCStrCast("G"), (getter)&FGetSets_Color::GetG, (setter)&FGetSets_Color::SetG, nullptr, nullptr },
	{ UPyCStrCast("R"), (getter)&FGetSets_Color::GetR, (setter)&FGetSets_Color::SetR, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_Color
{
	static int Color_Init_ArgCnt0_Overload0(FUPyWrapperColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		new (InSelf->StructInstance) FColor();
		return 0;
	}


	static int Color_Init_ArgCnt4_Overload0(FUPyWrapperColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		uint8 Arg0 = 0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			return -1;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return -1;
		}
		uint8 Arg1 = 0;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			return -1;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return -1;
		}
		uint8 Arg2 = 0;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			return -1;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return -1;
		}
		uint8 Arg3 = 0;
		if (!UPyConversion::Nativize(PyArg3, Arg3))
		{
			return -1;
		}

		new (InSelf->StructInstance) FColor(Arg0, Arg1, Arg2, Arg3);
		return 0;
	}


	static int Color_Init_ArgCnt1_Overload0(FUPyWrapperColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return -1;
		}
		int32 Arg0 = 0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			return -1;
		}

		new (InSelf->StructInstance) FColor(Arg0);
		return 0;
	}


	static int Init(FUPyWrapperColor* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		const int BaseInit = FUPyWrapperStruct::Init(InSelf);
		if (BaseInit != 0)
		{
			return BaseInit;
		}

		switch (PyTuple_Size(InArgs))
		{
		case 0:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Color::Color_Init_ArgCnt0_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		case 1:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Color::Color_Init_ArgCnt1_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		case 4:
		{
			if (
				UPyUtil::TryInit(InSelf, InArgs, InKwds, &FFuncs_Color::Color_Init_ArgCnt4_Overload0)
			)
			{
				return 0;
			}
			break;
		}
		default:
			break;
		}

		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::__init__"), TEXT("invalid argument"));
		return -1;
	}

	static int Color___eq___CmpAttempt0(FUPyWrapperColor* InSelf, PyObject* InOther)
	{
		FColor Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) == Arg0;
		return bResult ? 1 : 0;
	}

	static int Color___ne___CmpAttempt0(FUPyWrapperColor* InSelf, PyObject* InOther)
	{
		FColor Arg0;
		if (!UPyConversion::NativizeStructInstance(InOther, Arg0))
		{
			return -1;
		}

		const bool bResult = *(InSelf->ValuePtr()) != Arg0;
		return bResult ? 1 : 0;
	}

	static PyObject* RichCmp(FUPyWrapperColor* InSelf, PyObject* InOther, int InOp)
	{
		bool bHandled = false;
		bool bResult = false;
		switch (InOp)
		{
		case Py_EQ:
		{
			if (!bHandled)
			{
				int AttemptResult = Color___eq___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
			}
			break;
		}
		case Py_NE:
		{
			if (!bHandled)
			{
				int AttemptResult = Color___ne___CmpAttempt0(InSelf, InOther);
				if (AttemptResult >= 0)
				{
					bHandled = true;
					bResult = AttemptResult != 0;
				}
			}
			break;
		}
		default:
			break;
		}
		if (!bHandled)
		{
			Py_RETURN_NOTIMPLEMENTED;
		}
		if (bResult)
		{
			Py_RETURN_TRUE;
		}
		Py_RETURN_FALSE;
	}
};

struct FNumberFuncs_Color
{
	static PyObject* Op_iadd_Attempt0(FUPyWrapperColor* InSelf, PyObject* InRHS)
	{
		FColor Arg0;
		if (!UPyConversion::NativizeStructInstance(InRHS, Arg0))
		{
			return nullptr;
		}

		InSelf->ValuePtr()->operator+=(Arg0);
		Py_INCREF(InSelf);
		return (PyObject*)InSelf;
	}

	static PyObject* Op_iadd(FUPyWrapperColor* InSelf, PyObject* InRHS)
	{
		{
			PyObject* AttemptResult = Op_iadd_Attempt0(InSelf, InRHS);
			if (AttemptResult != nullptr)
			{
				return AttemptResult;
			}
			PyErr_Clear();
		}
		UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::__iadd__"), TEXT("operator not supported"));
		return nullptr;
	}

};

struct FMethods_Color
{
	static PyObject* CallFromHex(FUPyWrapperColor* InSelf, PyObject* InArg)
	{
		FString Arg0;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::FromHex"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = FColor::FromHex(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallMakeFromColorTemperature(FUPyWrapperColor* InSelf, PyObject* InArg)
	{
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::MakeFromColorTemperature"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = FColor::MakeFromColorTemperature(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallMakeRandomColor(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = FColor::MakeRandomColor();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallMakeRedToGreenColorFromScalar(FUPyWrapperColor* InSelf, PyObject* InArg)
	{
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::MakeRedToGreenColorFromScalar"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = FColor::MakeRedToGreenColorFromScalar(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallToHex(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToHex();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallToPackedABGR(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToPackedABGR();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallToPackedARGB(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToPackedARGB();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallToPackedBGRA(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToPackedBGRA();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallToPackedRGBA(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToPackedRGBA();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallToString(FUPyWrapperColor* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->ToString();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallWithAlpha(FUPyWrapperColor* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		uint8 Arg0 = 0;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Color::WithAlpha"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = InSelf->ValuePtr()->WithAlpha(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

};


static PyMethodDef FUPyWrapperColorPyMethodDefs[] = {
	{ "FromHex", UPyCFunctionCast(&FMethods_Color::CallFromHex), METH_O | METH_STATIC, nullptr },
	{ "MakeFromColorTemperature", UPyCFunctionCast(&FMethods_Color::CallMakeFromColorTemperature), METH_O | METH_STATIC, nullptr },
	{ "MakeRandomColor", UPyCFunctionCast(&FMethods_Color::CallMakeRandomColor), METH_NOARGS | METH_STATIC, nullptr },
	{ "MakeRedToGreenColorFromScalar", UPyCFunctionCast(&FMethods_Color::CallMakeRedToGreenColorFromScalar), METH_O | METH_STATIC, nullptr },
	{ "ToHex", UPyCFunctionCast(&FMethods_Color::CallToHex), METH_NOARGS, nullptr },
	{ "ToPackedABGR", UPyCFunctionCast(&FMethods_Color::CallToPackedABGR), METH_NOARGS, nullptr },
	{ "ToPackedARGB", UPyCFunctionCast(&FMethods_Color::CallToPackedARGB), METH_NOARGS, nullptr },
	{ "ToPackedBGRA", UPyCFunctionCast(&FMethods_Color::CallToPackedBGRA), METH_NOARGS, nullptr },
	{ "ToPackedRGBA", UPyCFunctionCast(&FMethods_Color::CallToPackedRGBA), METH_NOARGS, nullptr },
	{ "ToString", UPyCFunctionCast(&FMethods_Color::CallToString), METH_NOARGS, nullptr },
	{ "WithAlpha", UPyCFunctionCast(&FMethods_Color::CallWithAlpha), METH_O, nullptr },
	{ nullptr }
};

struct FConstants_Color
{
	static PyObject* GetConstant_Black(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Black;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Blue(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Blue;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Cyan(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Cyan;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Emerald(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Emerald;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Green(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Green;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Magenta(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Magenta;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Orange(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Orange;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Purple(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Purple;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Red(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Red;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Silver(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Silver;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Transparent(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Transparent;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Turquoise(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Turquoise;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_White(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::White;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* GetConstant_Yellow(PyTypeObject* InType, const void* InContext)
	{
		const auto Result = FColor::Yellow;
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static FUPyConstantDef* Table()
	{
		static FUPyConstantDef Constants[] = {
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Black, UPyCStrCast("Black"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Blue, UPyCStrCast("Blue"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Cyan, UPyCStrCast("Cyan"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Emerald, UPyCStrCast("Emerald"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Green, UPyCStrCast("Green"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Magenta, UPyCStrCast("Magenta"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Orange, UPyCStrCast("Orange"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Purple, UPyCStrCast("Purple"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Red, UPyCStrCast("Red"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Silver, UPyCStrCast("Silver"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Transparent, UPyCStrCast("Transparent"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Turquoise, UPyCStrCast("Turquoise"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_White, UPyCStrCast("White"), nullptr },
		{ nullptr, (PyConstantGetter)&FConstants_Color::GetConstant_Yellow, UPyCStrCast("Yellow"), nullptr },
			{ nullptr, nullptr, nullptr, nullptr }
		};
		return Constants;
	}
};


PyTypeObject* DoInitWrapperColor(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperColorType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_Color::Init;
	PyType->tp_methods = FUPyWrapperColorPyMethodDefs;
	PyType->tp_getset = FUPyWrapperColorGetSets;
	PyType->tp_richcompare = (richcmpfunc)&FFuncs_Color::RichCmp;
	static PyNumberMethods PyNumber;
	PyNumber.nb_inplace_add = (binaryfunc)&FNumberFuncs_Color::Op_iadd;
	PyType->tp_as_number = &PyNumber;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyConstantDef::AddConstantsToType(FConstants_Color::Table(), PyType);
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperColor(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterInlineStructFactory(StaticCastSharedRef<const IUPyWrapperInlineStructFactory>(MakeShared<TUPyWrapperInlineStructFactory<FColor>>()));
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FColor>::Get(), DoInitWrapperColor);
}

PyObject* FUPyWrapperColor::CreateInstance(const FColor& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperColorType, TBaseStructure<FColor>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperColor* UPyIsColor(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperColorType))
	{
		return (FUPyWrapperColor*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FColor& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperColor* PyVector = UPyIsColor(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FColor'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
	
	FUPyConversionResult PythonizeStructInstance(const FColor& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperColor::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
