
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperStruct.h"
#include "Utils/UPyGenUtil.h"
#include "Components/SlateWrapperTypes.h"


/** Python type for FUPyWrapperEventReply */
extern PyTypeObject UPyWrapperEventReplyType;

/** Initialize the UPyWrapperEventReplyType types and add them to the given Python module */
void InitializeUPyWrapperEventReply(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperEventReply: public FUPyWrapperStruct
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperEventReplyType;
	}

	UNREALPYTHON_API FEventReply* ValuePtr() const
	{
		return static_cast<FEventReply*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const FEventReply& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API FUPyWrapperEventReply* UPyIsEventReply(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FEventReply& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const FEventReply& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
