
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/Slate/Struct/UPyWrapperAnchors.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Templates/SharedPointer.h"
#include "UObject/NoExportTypes.h"


PyTypeObject UPyWrapperAnchorsType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Anchors", /* tp_name */
	sizeof(FUPyWrapperAnchors), /* tp_basicsize */
};

struct FGetSets_Anchors
{
	static PyObject* GetMaximum(FUPyWrapperAnchors* InSelf, void* InClosure)
	{
		if (!FUPyWrapperAnchors::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector2D>::Get(), (void*)&InSelf->ValuePtr()->Maximum, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetMaximum(FUPyWrapperAnchors* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperAnchors::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->Maximum))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Anchors::Maximum"), TEXT("value is not a compatible struct"));
		return -1;
	}

	static PyObject* GetMinimum(FUPyWrapperAnchors* InSelf, void* InClosure)
	{
		if (!FUPyWrapperAnchors::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(TBaseStructure<FVector2D>::Get(), (void*)&InSelf->ValuePtr()->Minimum, FUPyWrapperOwnerContext((PyObject*)InSelf), EUPyConversionMethod::Reference);
	}

	static int SetMinimum(FUPyWrapperAnchors* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperAnchors::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeStructInstance(InValue, InSelf->ValuePtr()->Minimum))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Anchors::Minimum"), TEXT("value is not a compatible struct"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperAnchorsGetSets[] = {
	{ UPyCStrCast("Maximum"), (getter)&FGetSets_Anchors::GetMaximum, (setter)&FGetSets_Anchors::SetMaximum, nullptr, nullptr },
	{ UPyCStrCast("Minimum"), (getter)&FGetSets_Anchors::GetMinimum, (setter)&FGetSets_Anchors::SetMinimum, nullptr, nullptr },
	{ nullptr }
};

struct FFuncs_Anchors
{
	static int Init(FUPyWrapperAnchors* InSelf, PyObject* InArgs, PyObject* InKwds)
	{
		return FUPyWrapperStruct::Init(InSelf);
	}
};





PyTypeObject* DoInitWrapperAnchors(const UScriptStruct* InStruct, PyTypeObject* InSuperType)
{
	if (InStruct == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedStructType(InStruct))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedStructType(InStruct));
	}

	PyTypeObject* PyType = &UPyWrapperAnchorsType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperStructType;
	PyType->tp_init = (initproc)&FFuncs_Anchors::Init;
	PyType->tp_getset = FUPyWrapperAnchorsGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedStructType(InStruct, PyType);
		return PyType;
	}

	return nullptr;

}

void InitializeUPyWrapperAnchors(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterInlineStructFactory(StaticCastSharedRef<const IUPyWrapperInlineStructFactory>(MakeShared<TUPyWrapperInlineStructFactory<FAnchors>>()));
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedStructCreateFunc(TBaseStructure<FAnchors>::Get(), DoInitWrapperAnchors);
}

PyObject* FUPyWrapperAnchors::CreateInstance(const FAnchors& InValue, const FUPyWrapperOwnerContext& InOwnerContext, const EUPyConversionMethod InConversionMethod)
{
	return (PyObject*)FUPyWrapperStructFactory::Get().CreateInstance(&UPyWrapperAnchorsType, TBaseStructure<FAnchors>::Get(), (void*)&InValue, InOwnerContext, InConversionMethod);
}

FUPyWrapperAnchors* UPyIsAnchors(PyObject* InSelf)
{
	if (InSelf && PyObject_TypeCheck(InSelf, &UPyWrapperAnchorsType))
	{
		return (FUPyWrapperAnchors*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult NativizeStructInstance(PyObject* PyObj, FAnchors& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperAnchors* PyVector = UPyIsAnchors(PyObj))
		{
			OutVal = *PyVector->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("NativizeStructInstance"), *FString::Printf(TEXT("Cannot nativize '%s' as 'FAnchors'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
	
	FUPyConversionResult PythonizeStructInstance(const FAnchors& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState)
	{
		OutPyObj = FUPyWrapperAnchors::CreateInstance(InVal, FUPyWrapperOwnerContext(), EUPyConversionMethod::Copy);
		return FUPyConversionResult::Success();
	}
}
