
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/UMG/Class/UPyWrapperWidget.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Layout/Geometry.h"
#include "Layout/Clipping.h"
#include "UObject/NoExportTypes.h"
#include "Engine/GameInstance.h"
#include "Engine/LocalPlayer.h"
#include "GameFramework/PlayerController.h"
#include "Components/PanelWidget.h"
#include "Slate/WidgetTransform.h"
#include "Components/SlateWrapperTypes.h"
#include "FieldNotificationId.h"
#include "Input/NavigationReply.h"
#include "Types/SlateEnums.h"
#include "Components/Widget.h"


PyTypeObject UPyWrapperWidgetType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"Widget", /* tp_name */
	sizeof(FUPyWrapperWidget), /* tp_basicsize */
};

struct FGetSets_Widget
{
#if WITH_EDITOR
	static PyObject* GetAccessibleBehavior(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::PythonizeEnumEntry((int64)InSelf->ValuePtr()->AccessibleBehavior, StaticEnum<ESlateAccessibleBehavior>());
	}

	static int SetAccessibleBehavior(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeEnumEntry(InValue, StaticEnum<ESlateAccessibleBehavior>(), InSelf->ValuePtr()->AccessibleBehavior))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::AccessibleBehavior"), TEXT("value is not compatible with this property"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static PyObject* GetAccessibleSummaryBehavior(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::PythonizeEnumEntry((int64)InSelf->ValuePtr()->AccessibleSummaryBehavior, StaticEnum<ESlateAccessibleBehavior>());
	}

	static int SetAccessibleSummaryBehavior(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeEnumEntry(InValue, StaticEnum<ESlateAccessibleBehavior>(), InSelf->ValuePtr()->AccessibleSummaryBehavior))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::AccessibleSummaryBehavior"), TEXT("value is not compatible with this property"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static PyObject* GetAccessibleSummaryText(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->AccessibleSummaryText);
	}

	static int SetAccessibleSummaryText(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->AccessibleSummaryText))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::AccessibleSummaryText"), TEXT("value is not Text"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AccessibleSummaryTextDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AccessibleSummaryTextDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAccessibleSummaryTextDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_AccessibleSummaryTextDelegate(), "AccessibleSummaryTextDelegate");
	}

	static int SetAccessibleSummaryTextDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_AccessibleSummaryTextDelegate(), "AccessibleSummaryTextDelegate");
	}

#endif
#if WITH_EDITOR
	static PyObject* GetAccessibleText(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->AccessibleText);
	}

	static int SetAccessibleText(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->AccessibleText))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::AccessibleText"), TEXT("value is not Text"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AccessibleTextDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AccessibleTextDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAccessibleTextDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_AccessibleTextDelegate(), "AccessibleTextDelegate");
	}

	static int SetAccessibleTextDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_AccessibleTextDelegate(), "AccessibleTextDelegate");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_AccessibleWidgetData()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("AccessibleWidgetData")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetAccessibleWidgetData(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_AccessibleWidgetData(), "AccessibleWidgetData");
	}

	static int SetAccessibleWidgetData(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_AccessibleWidgetData(), "AccessibleWidgetData");
	}

#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CategoryName()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CategoryName")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCategoryName(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_CategoryName(), "CategoryName");
	}

	static int SetCategoryName(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_CategoryName(), "CategoryName");
	}

#endif
#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_DesignerFlags()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("DesignerFlags")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetDesignerFlags(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_DesignerFlags(), "DesignerFlags");
	}

	static int SetDesignerFlags(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_DesignerFlags(), "DesignerFlags");
	}

#endif
#if WITH_EDITOR
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_DisplayLabel()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("DisplayLabel")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetDisplayLabel(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_DisplayLabel(), "DisplayLabel");
	}

	static int SetDisplayLabel(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_DisplayLabel(), "DisplayLabel");
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_NativeBindings()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("NativeBindings")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetNativeBindings(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_NativeBindings(), "NativeBindings");
	}

	static int SetNativeBindings(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_NativeBindings(), "NativeBindings");
	}

	static PyObject* GetNavigation(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->Navigation);
	}

	static int SetNavigation(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->Navigation))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::Navigation"), TEXT("value is not a compatible object"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_PixelSnapping()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("PixelSnapping")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetPixelSnapping(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_PixelSnapping(), "PixelSnapping");
	}

	static int SetPixelSnapping(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_PixelSnapping(), "PixelSnapping");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_RenderOpacity()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("RenderOpacity")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetRenderOpacity(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_RenderOpacity(), "RenderOpacity");
	}

	static int SetRenderOpacity(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_RenderOpacity(), "RenderOpacity");
	}

	static PyObject* GetSlot(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->Slot);
	}

	static int SetSlot(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::Nativize(InValue, InSelf->ValuePtr()->Slot))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::Slot"), TEXT("value is not a compatible object"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ToolTipTextDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ToolTipTextDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetToolTipTextDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_ToolTipTextDelegate(), "ToolTipTextDelegate");
	}

	static int SetToolTipTextDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_ToolTipTextDelegate(), "ToolTipTextDelegate");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_ToolTipWidgetDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("ToolTipWidgetDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetToolTipWidgetDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_ToolTipWidgetDelegate(), "ToolTipWidgetDelegate");
	}

	static int SetToolTipWidgetDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_ToolTipWidgetDelegate(), "ToolTipWidgetDelegate");
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_VisibilityDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("VisibilityDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetVisibilityDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_VisibilityDelegate(), "VisibilityDelegate");
	}

	static int SetVisibilityDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_VisibilityDelegate(), "VisibilityDelegate");
	}

#if WITH_EDITOR
	static PyObject* GetbCanChildrenBeAccessible(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bCanChildrenBeAccessible);
	}

	static int SetbCanChildrenBeAccessible(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bCanChildrenBeAccessible = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bCanChildrenBeAccessible"), TEXT("value is not bool"));
		return -1;
	}

#endif
	static PyObject* GetbCreatedByConstructionScript(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bCreatedByConstructionScript);
	}

	static int SetbCreatedByConstructionScript(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bCreatedByConstructionScript = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bCreatedByConstructionScript"), TEXT("value is not bool"));
		return -1;
	}

#if WITH_EDITOR
	static PyObject* GetbExpandedInDesigner(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bExpandedInDesigner);
	}

	static int SetbExpandedInDesigner(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bExpandedInDesigner = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bExpandedInDesigner"), TEXT("value is not bool"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static PyObject* GetbHiddenInDesigner(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bHiddenInDesigner);
	}

	static int SetbHiddenInDesigner(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bHiddenInDesigner = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bHiddenInDesigner"), TEXT("value is not bool"));
		return -1;
	}

#endif
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_bIsEnabledDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("bIsEnabledDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetbIsEnabledDelegate(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_bIsEnabledDelegate(), "bIsEnabledDelegate");
	}

	static int SetbIsEnabledDelegate(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_bIsEnabledDelegate(), "bIsEnabledDelegate");
	}

	static PyObject* GetbIsVariable(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bIsVariable);
	}

	static int SetbIsVariable(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bIsVariable = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bIsVariable"), TEXT("value is not bool"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_bIsVolatile()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UWidget::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("bIsVolatile")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetbIsVolatile(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObjectBase::GetPropertyValue(InSelf, GetPropertyDef_bIsVolatile(), "bIsVolatile");
	}

	static int SetbIsVolatile(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObjectBase::SetPropertyValue(InSelf, InValue, GetPropertyDef_bIsVolatile(), "bIsVolatile");
	}

#if WITH_EDITOR
	static PyObject* GetbLockedInDesigner(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bLockedInDesigner);
	}

	static int SetbLockedInDesigner(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bLockedInDesigner = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bLockedInDesigner"), TEXT("value is not bool"));
		return -1;
	}

#endif
#if WITH_EDITOR
	static PyObject* GetbOverrideAccessibleDefaults(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bOverrideAccessibleDefaults);
	}

	static int SetbOverrideAccessibleDefaults(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bOverrideAccessibleDefaults = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bOverrideAccessibleDefaults"), TEXT("value is not bool"));
		return -1;
	}

#endif
	static PyObject* GetbOverride_Cursor(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bOverride_Cursor);
	}

	static int SetbOverride_Cursor(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bOverride_Cursor = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bOverride_Cursor"), TEXT("value is not bool"));
		return -1;
	}

	static PyObject* GetbWrappedByComponent(FUPyWrapperWidget* InSelf, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::Pythonize(InSelf->ValuePtr()->bWrappedByComponent);
	}

	static int SetbWrappedByComponent(FUPyWrapperWidget* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperObjectBase::ValidateInternalState(InSelf))
		{
			return -1;
		}
		bool bTemp = false;
		if (UPyConversion::Nativize(InValue, bTemp))
		{
			InSelf->ValuePtr()->bWrappedByComponent = bTemp;
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("Widget::bWrappedByComponent"), TEXT("value is not bool"));
		return -1;
	}

};


static PyGetSetDef FUPyWrapperWidgetGetSets[] = {
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleBehavior"), (getter)&FGetSets_Widget::GetAccessibleBehavior, (setter)&FGetSets_Widget::SetAccessibleBehavior, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleSummaryBehavior"), (getter)&FGetSets_Widget::GetAccessibleSummaryBehavior, (setter)&FGetSets_Widget::SetAccessibleSummaryBehavior, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleSummaryText"), (getter)&FGetSets_Widget::GetAccessibleSummaryText, (setter)&FGetSets_Widget::SetAccessibleSummaryText, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleSummaryTextDelegate"), (getter)&FGetSets_Widget::GetAccessibleSummaryTextDelegate, (setter)&FGetSets_Widget::SetAccessibleSummaryTextDelegate, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleText"), (getter)&FGetSets_Widget::GetAccessibleText, (setter)&FGetSets_Widget::SetAccessibleText, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("AccessibleTextDelegate"), (getter)&FGetSets_Widget::GetAccessibleTextDelegate, (setter)&FGetSets_Widget::SetAccessibleTextDelegate, nullptr, nullptr },
#endif
	{ UPyCStrCast("AccessibleWidgetData"), (getter)&FGetSets_Widget::GetAccessibleWidgetData, (setter)&FGetSets_Widget::SetAccessibleWidgetData, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("CategoryName"), (getter)&FGetSets_Widget::GetCategoryName, (setter)&FGetSets_Widget::SetCategoryName, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("DesignerFlags"), (getter)&FGetSets_Widget::GetDesignerFlags, (setter)&FGetSets_Widget::SetDesignerFlags, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("DisplayLabel"), (getter)&FGetSets_Widget::GetDisplayLabel, (setter)&FGetSets_Widget::SetDisplayLabel, nullptr, nullptr },
#endif
	{ UPyCStrCast("NativeBindings"), (getter)&FGetSets_Widget::GetNativeBindings, (setter)&FGetSets_Widget::SetNativeBindings, nullptr, nullptr },
	{ UPyCStrCast("Navigation"), (getter)&FGetSets_Widget::GetNavigation, (setter)&FGetSets_Widget::SetNavigation, nullptr, nullptr },
	{ UPyCStrCast("PixelSnapping"), (getter)&FGetSets_Widget::GetPixelSnapping, (setter)&FGetSets_Widget::SetPixelSnapping, nullptr, nullptr },
	{ UPyCStrCast("RenderOpacity"), (getter)&FGetSets_Widget::GetRenderOpacity, (setter)&FGetSets_Widget::SetRenderOpacity, nullptr, nullptr },
	{ UPyCStrCast("Slot"), (getter)&FGetSets_Widget::GetSlot, (setter)&FGetSets_Widget::SetSlot, nullptr, nullptr },
	{ UPyCStrCast("ToolTipTextDelegate"), (getter)&FGetSets_Widget::GetToolTipTextDelegate, (setter)&FGetSets_Widget::SetToolTipTextDelegate, nullptr, nullptr },
	{ UPyCStrCast("ToolTipWidgetDelegate"), (getter)&FGetSets_Widget::GetToolTipWidgetDelegate, (setter)&FGetSets_Widget::SetToolTipWidgetDelegate, nullptr, nullptr },
	{ UPyCStrCast("VisibilityDelegate"), (getter)&FGetSets_Widget::GetVisibilityDelegate, (setter)&FGetSets_Widget::SetVisibilityDelegate, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("bCanChildrenBeAccessible"), (getter)&FGetSets_Widget::GetbCanChildrenBeAccessible, (setter)&FGetSets_Widget::SetbCanChildrenBeAccessible, nullptr, nullptr },
#endif
	{ UPyCStrCast("bCreatedByConstructionScript"), (getter)&FGetSets_Widget::GetbCreatedByConstructionScript, (setter)&FGetSets_Widget::SetbCreatedByConstructionScript, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("bExpandedInDesigner"), (getter)&FGetSets_Widget::GetbExpandedInDesigner, (setter)&FGetSets_Widget::SetbExpandedInDesigner, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("bHiddenInDesigner"), (getter)&FGetSets_Widget::GetbHiddenInDesigner, (setter)&FGetSets_Widget::SetbHiddenInDesigner, nullptr, nullptr },
#endif
	{ UPyCStrCast("bIsEnabledDelegate"), (getter)&FGetSets_Widget::GetbIsEnabledDelegate, (setter)&FGetSets_Widget::SetbIsEnabledDelegate, nullptr, nullptr },
	{ UPyCStrCast("bIsVariable"), (getter)&FGetSets_Widget::GetbIsVariable, (setter)&FGetSets_Widget::SetbIsVariable, nullptr, nullptr },
	{ UPyCStrCast("bIsVolatile"), (getter)&FGetSets_Widget::GetbIsVolatile, (setter)&FGetSets_Widget::SetbIsVolatile, nullptr, nullptr },
#if WITH_EDITOR
	{ UPyCStrCast("bLockedInDesigner"), (getter)&FGetSets_Widget::GetbLockedInDesigner, (setter)&FGetSets_Widget::SetbLockedInDesigner, nullptr, nullptr },
#endif
#if WITH_EDITOR
	{ UPyCStrCast("bOverrideAccessibleDefaults"), (getter)&FGetSets_Widget::GetbOverrideAccessibleDefaults, (setter)&FGetSets_Widget::SetbOverrideAccessibleDefaults, nullptr, nullptr },
#endif
	{ UPyCStrCast("bOverride_Cursor"), (getter)&FGetSets_Widget::GetbOverride_Cursor, (setter)&FGetSets_Widget::SetbOverride_Cursor, nullptr, nullptr },
	{ UPyCStrCast("bWrappedByComponent"), (getter)&FGetSets_Widget::GetbWrappedByComponent, (setter)&FGetSets_Widget::SetbWrappedByComponent, nullptr, nullptr },
	{ nullptr }
};



struct FMethods_Widget
{
	static PyObject* CallForceLayoutPrepass(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->ForceLayoutPrepass();
		Py_RETURN_NONE;
	}

	static PyObject* CallForceVolatile(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		bool Arg0 = false;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::ForceVolatile"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->ForceVolatile(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallGetAccessibleSummaryText(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetAccessibleSummaryText();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetAccessibleText(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetAccessibleText();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetCachedGeometry(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetCachedGeometry();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetClipping(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetClipping();
		return UPyConversion::PythonizeEnumEntry((int64)Result, StaticEnum<EWidgetClipping>());
	}

	static PyObject* CallGetDesiredSize(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetDesiredSize();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetGameInstance(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetGameInstance();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetIsEnabled(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->GetIsEnabled();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallGetOwningLocalPlayer(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetOwningLocalPlayer();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetOwningPlayer(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetOwningPlayer();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetPaintSpaceGeometry(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetPaintSpaceGeometry();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetParent(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetParent();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetRenderOpacity(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetRenderOpacity();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetRenderTransform(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetRenderTransform();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetRenderTransformAngle(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetRenderTransformAngle();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetTickSpaceGeometry(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetTickSpaceGeometry();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetVisibility(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetVisibility();
		return UPyConversion::PythonizeEnumEntry((int64)Result, StaticEnum<ESlateVisibility>());
	}

	static PyObject* CallHasAnyUserFocus(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->HasAnyUserFocus();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasFocusedDescendants(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->HasFocusedDescendants();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasKeyboardFocus(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->HasKeyboardFocus();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasMouseCapture(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->HasMouseCapture();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasMouseCaptureByUser(FUPyWrapperWidget* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		int32 Arg0 = 0;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::HasMouseCaptureByUser"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		int32 Arg1 = -1;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::HasMouseCaptureByUser"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		const bool bResult = InSelf->ValuePtr()->HasMouseCaptureByUser(Arg0, Arg1);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasUserFocus(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::HasUserFocus"), TEXT("invalid argument"));
			return nullptr;
		}

		const bool bResult = InSelf->ValuePtr()->HasUserFocus(Arg0);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallHasUserFocusedDescendants(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::HasUserFocusedDescendants"), TEXT("invalid argument"));
			return nullptr;
		}

		const bool bResult = InSelf->ValuePtr()->HasUserFocusedDescendants(Arg0);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallInvalidateLayoutAndVolatility(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->InvalidateLayoutAndVolatility();
		Py_RETURN_NONE;
	}

	static PyObject* CallIsHovered(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsHovered();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallIsInViewport(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsInViewport();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallIsRendered(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsRendered();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallIsVisible(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsVisible();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallK2_AddFieldValueChangedDelegate(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InArgs))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("Widget::K2_AddFieldValueChangedDelegate"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallK2_BroadcastFieldValueChanged(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FFieldNotificationId Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::K2_BroadcastFieldValueChanged"), TEXT("invalid argument"));
			return nullptr;
		}

		static UFunction* Func = UWidget::StaticClass()->FindFunctionByName(TEXT("K2_BroadcastFieldValueChanged"));
		static FProperty* Prop_FieldId = Func ? Func->FindPropertyByName(TEXT("FieldId")) : nullptr;
		if (Func)
		{
			uint8* Parms = (uint8*)FMemory::Malloc(Func->ParmsSize);
			FMemory::Memzero(Parms, Func->ParmsSize);
			if (Prop_FieldId)
			{
				Prop_FieldId->CopyCompleteValue_InContainer(Parms, &Arg0);
			}
			InSelf->ValuePtr()->ProcessEvent(Func, Parms);
			FMemory::Free(Parms);
		}
		Py_RETURN_NONE;
	}

	static PyObject* CallK2_RemoveFieldValueChangedDelegate(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InArgs))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("Widget::K2_RemoveFieldValueChangedDelegate"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallRemoveFromParent(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->RemoveFromParent();
		Py_RETURN_NONE;
	}

	static PyObject* CallResetCursor(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->ResetCursor();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetAllNavigationRules(FUPyWrapperWidget* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		EUINavigationRule Arg0;
		if (!UPyConversion::NativizeEnumEntry(PyArg0, StaticEnum<EUINavigationRule>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetAllNavigationRules"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FName Arg1;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetAllNavigationRules"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetAllNavigationRules(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetClipping(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		EWidgetClipping Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<EWidgetClipping>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetClipping"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetClipping(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetCursor(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		EMouseCursor::Type Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<EMouseCursor::Type>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetCursor"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetCursor(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetFocus(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->SetFocus();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetIsEnabled(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		bool Arg0 = false;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetIsEnabled"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetIsEnabled(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetKeyboardFocus(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		InSelf->ValuePtr()->SetKeyboardFocus();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetNavigationRuleBase(FUPyWrapperWidget* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		EUINavigation Arg0;
		if (!UPyConversion::NativizeEnumEntry(PyArg0, StaticEnum<EUINavigation>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetNavigationRuleBase"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		EUINavigationRule Arg1;
		if (!UPyConversion::NativizeEnumEntry(PyArg1, StaticEnum<EUINavigationRule>(), Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetNavigationRuleBase"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetNavigationRuleBase(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetNavigationRuleCustom(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InArgs))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("Widget::SetNavigationRuleCustom"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallSetNavigationRuleCustomBoundary(FUPyWrapperWidget* InSelf, PyObject* Py_UNUSED(InArgs))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("Widget::SetNavigationRuleCustomBoundary"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallSetNavigationRuleExplicit(FUPyWrapperWidget* InSelf, PyObject* InArgs)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		EUINavigation Arg0;
		if (!UPyConversion::NativizeEnumEntry(PyArg0, StaticEnum<EUINavigation>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetNavigationRuleExplicit"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetNavigationRuleExplicit"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetNavigationRuleExplicit(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderOpacity(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderOpacity"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderOpacity(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderScale(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector2D Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderScale"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderScale(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderShear(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector2D Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderShear"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderShear(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderTransform(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FWidgetTransform Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderTransform"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderTransform(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderTransformAngle(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		float Arg0 = 0.0f;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderTransformAngle"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderTransformAngle(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderTransformPivot(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector2D Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderTransformPivot"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderTransformPivot(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetRenderTranslation(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FVector2D Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetRenderTranslation"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetRenderTranslation(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetToolTip(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetToolTip"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetToolTip(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetToolTipText(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		FText Arg0;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetToolTipText"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetToolTipText(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetUserFocus(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetUserFocus"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetUserFocus(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetVisibility(FUPyWrapperWidget* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		ESlateVisibility Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<ESlateVisibility>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("Widget::SetVisibility"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetVisibility(Arg0);
		Py_RETURN_NONE;
	}

};


static PyMethodDef FUPyWrapperWidgetPyMethodDefs[] = {
	{ "ForceLayoutPrepass", UPyCFunctionCast(&FMethods_Widget::CallForceLayoutPrepass), METH_NOARGS, nullptr },
	{ "ForceVolatile", UPyCFunctionCast(&FMethods_Widget::CallForceVolatile), METH_O, nullptr },
	{ "GetAccessibleSummaryText", UPyCFunctionCast(&FMethods_Widget::CallGetAccessibleSummaryText), METH_NOARGS, nullptr },
	{ "GetAccessibleText", UPyCFunctionCast(&FMethods_Widget::CallGetAccessibleText), METH_NOARGS, nullptr },
	{ "GetCachedGeometry", UPyCFunctionCast(&FMethods_Widget::CallGetCachedGeometry), METH_NOARGS, nullptr },
	{ "GetClipping", UPyCFunctionCast(&FMethods_Widget::CallGetClipping), METH_NOARGS, nullptr },
	{ "GetDesiredSize", UPyCFunctionCast(&FMethods_Widget::CallGetDesiredSize), METH_NOARGS, nullptr },
	{ "GetGameInstance", UPyCFunctionCast(&FMethods_Widget::CallGetGameInstance), METH_NOARGS, nullptr },
	{ "GetIsEnabled", UPyCFunctionCast(&FMethods_Widget::CallGetIsEnabled), METH_NOARGS, nullptr },
	{ "GetOwningLocalPlayer", UPyCFunctionCast(&FMethods_Widget::CallGetOwningLocalPlayer), METH_NOARGS, nullptr },
	{ "GetOwningPlayer", UPyCFunctionCast(&FMethods_Widget::CallGetOwningPlayer), METH_NOARGS, nullptr },
	{ "GetPaintSpaceGeometry", UPyCFunctionCast(&FMethods_Widget::CallGetPaintSpaceGeometry), METH_NOARGS, nullptr },
	{ "GetParent", UPyCFunctionCast(&FMethods_Widget::CallGetParent), METH_NOARGS, nullptr },
	{ "GetRenderOpacity", UPyCFunctionCast(&FMethods_Widget::CallGetRenderOpacity), METH_NOARGS, nullptr },
	{ "GetRenderTransform", UPyCFunctionCast(&FMethods_Widget::CallGetRenderTransform), METH_NOARGS, nullptr },
	{ "GetRenderTransformAngle", UPyCFunctionCast(&FMethods_Widget::CallGetRenderTransformAngle), METH_NOARGS, nullptr },
	{ "GetTickSpaceGeometry", UPyCFunctionCast(&FMethods_Widget::CallGetTickSpaceGeometry), METH_NOARGS, nullptr },
	{ "GetVisibility", UPyCFunctionCast(&FMethods_Widget::CallGetVisibility), METH_NOARGS, nullptr },
	{ "HasAnyUserFocus", UPyCFunctionCast(&FMethods_Widget::CallHasAnyUserFocus), METH_NOARGS, nullptr },
	{ "HasFocusedDescendants", UPyCFunctionCast(&FMethods_Widget::CallHasFocusedDescendants), METH_NOARGS, nullptr },
	{ "HasKeyboardFocus", UPyCFunctionCast(&FMethods_Widget::CallHasKeyboardFocus), METH_NOARGS, nullptr },
	{ "HasMouseCapture", UPyCFunctionCast(&FMethods_Widget::CallHasMouseCapture), METH_NOARGS, nullptr },
	{ "HasMouseCaptureByUser", UPyCFunctionCast(&FMethods_Widget::CallHasMouseCaptureByUser), METH_VARARGS, nullptr },
	{ "HasUserFocus", UPyCFunctionCast(&FMethods_Widget::CallHasUserFocus), METH_O, nullptr },
	{ "HasUserFocusedDescendants", UPyCFunctionCast(&FMethods_Widget::CallHasUserFocusedDescendants), METH_O, nullptr },
	{ "InvalidateLayoutAndVolatility", UPyCFunctionCast(&FMethods_Widget::CallInvalidateLayoutAndVolatility), METH_NOARGS, nullptr },
	{ "IsHovered", UPyCFunctionCast(&FMethods_Widget::CallIsHovered), METH_NOARGS, nullptr },
	{ "IsInViewport", UPyCFunctionCast(&FMethods_Widget::CallIsInViewport), METH_NOARGS, nullptr },
	{ "IsRendered", UPyCFunctionCast(&FMethods_Widget::CallIsRendered), METH_NOARGS, nullptr },
	{ "IsVisible", UPyCFunctionCast(&FMethods_Widget::CallIsVisible), METH_NOARGS, nullptr },
	{ "K2_AddFieldValueChangedDelegate", UPyCFunctionCast(&FMethods_Widget::CallK2_AddFieldValueChangedDelegate), METH_VARARGS, nullptr },
	{ "K2_BroadcastFieldValueChanged", UPyCFunctionCast(&FMethods_Widget::CallK2_BroadcastFieldValueChanged), METH_O, nullptr },
	{ "K2_RemoveFieldValueChangedDelegate", UPyCFunctionCast(&FMethods_Widget::CallK2_RemoveFieldValueChangedDelegate), METH_VARARGS, nullptr },
	{ "RemoveFromParent", UPyCFunctionCast(&FMethods_Widget::CallRemoveFromParent), METH_NOARGS, nullptr },
	{ "ResetCursor", UPyCFunctionCast(&FMethods_Widget::CallResetCursor), METH_NOARGS, nullptr },
	{ "SetAllNavigationRules", UPyCFunctionCast(&FMethods_Widget::CallSetAllNavigationRules), METH_VARARGS, nullptr },
	{ "SetClipping", UPyCFunctionCast(&FMethods_Widget::CallSetClipping), METH_O, nullptr },
	{ "SetCursor", UPyCFunctionCast(&FMethods_Widget::CallSetCursor), METH_O, nullptr },
	{ "SetFocus", UPyCFunctionCast(&FMethods_Widget::CallSetFocus), METH_NOARGS, nullptr },
	{ "SetIsEnabled", UPyCFunctionCast(&FMethods_Widget::CallSetIsEnabled), METH_O, nullptr },
	{ "SetKeyboardFocus", UPyCFunctionCast(&FMethods_Widget::CallSetKeyboardFocus), METH_NOARGS, nullptr },
	{ "SetNavigationRuleBase", UPyCFunctionCast(&FMethods_Widget::CallSetNavigationRuleBase), METH_VARARGS, nullptr },
	{ "SetNavigationRuleCustom", UPyCFunctionCast(&FMethods_Widget::CallSetNavigationRuleCustom), METH_VARARGS, nullptr },
	{ "SetNavigationRuleCustomBoundary", UPyCFunctionCast(&FMethods_Widget::CallSetNavigationRuleCustomBoundary), METH_VARARGS, nullptr },
	{ "SetNavigationRuleExplicit", UPyCFunctionCast(&FMethods_Widget::CallSetNavigationRuleExplicit), METH_VARARGS, nullptr },
	{ "SetRenderOpacity", UPyCFunctionCast(&FMethods_Widget::CallSetRenderOpacity), METH_O, nullptr },
	{ "SetRenderScale", UPyCFunctionCast(&FMethods_Widget::CallSetRenderScale), METH_O, nullptr },
	{ "SetRenderShear", UPyCFunctionCast(&FMethods_Widget::CallSetRenderShear), METH_O, nullptr },
	{ "SetRenderTransform", UPyCFunctionCast(&FMethods_Widget::CallSetRenderTransform), METH_O, nullptr },
	{ "SetRenderTransformAngle", UPyCFunctionCast(&FMethods_Widget::CallSetRenderTransformAngle), METH_O, nullptr },
	{ "SetRenderTransformPivot", UPyCFunctionCast(&FMethods_Widget::CallSetRenderTransformPivot), METH_O, nullptr },
	{ "SetRenderTranslation", UPyCFunctionCast(&FMethods_Widget::CallSetRenderTranslation), METH_O, nullptr },
	{ "SetToolTip", UPyCFunctionCast(&FMethods_Widget::CallSetToolTip), METH_O, nullptr },
	{ "SetToolTipText", UPyCFunctionCast(&FMethods_Widget::CallSetToolTipText), METH_O, nullptr },
	{ "SetUserFocus", UPyCFunctionCast(&FMethods_Widget::CallSetUserFocus), METH_O, nullptr },
	{ "SetVisibility", UPyCFunctionCast(&FMethods_Widget::CallSetVisibility), METH_O, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperWidget(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperWidgetType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperWidgetPyMethodDefs;
	PyType->tp_getset = FUPyWrapperWidgetGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperWidget(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UWidget::StaticClass(), DoInitWrapperWidget);
}

FUPyWrapperWidget* UPyIsWidget(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperWidgetType))
	{
		return (FUPyWrapperWidget*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UWidget*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperWidget* PyWidget = UPyIsWidget(PyObj))
		{
			if (!FUPyWrapperObjectBase::ValidateInternalState(PyWidget))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyWidget->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UWidget'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
