
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/HorizontalBox.h"


/** Python type for FUPyWrapperHorizontalBox */
extern PyTypeObject UPyWrapperHorizontalBoxType;

/** Initialize the UPyWrapperHorizontalBoxType types and add them to the given Python module */
void InitializeUPyWrapperHorizontalBox(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperHorizontalBox: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperHorizontalBoxType;
	}

	UNREALPYTHON_API UHorizontalBox* ValuePtr() const
	{
		return Cast<UHorizontalBox>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperHorizontalBox* UPyIsHorizontalBox(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UHorizontalBox*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
