
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/ListViewBase.h"


/** Python type for FUPyWrapperListViewBase */
extern PyTypeObject UPyWrapperListViewBaseType;

/** Initialize the UPyWrapperListViewBaseType types and add them to the given Python module */
void InitializeUPyWrapperListViewBase(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperListViewBase: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperListViewBaseType;
	}

	UNREALPYTHON_API UListViewBase* ValuePtr() const
	{
		return Cast<UListViewBase>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperListViewBase* UPyIsListViewBase(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UListViewBase*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
