
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/EditableTextBox.h"


/** Python type for FUPyWrapperEditableTextBox */
extern PyTypeObject UPyWrapperEditableTextBoxType;

/** Initialize the UPyWrapperEditableTextBoxType types and add them to the given Python module */
void InitializeUPyWrapperEditableTextBox(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperEditableTextBox: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperEditableTextBoxType;
	}

	UNREALPYTHON_API UEditableTextBox* ValuePtr() const
	{
		return Cast<UEditableTextBox>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperEditableTextBox* UPyIsEditableTextBox(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UEditableTextBox*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
