
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/UMG/Class/UPyWrapperCheckBox.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Styling/SlateTypes.h"
#include "Types/SlateEnums.h"


PyTypeObject UPyWrapperCheckBoxType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"CheckBox", /* tp_name */
	sizeof(FUPyWrapperCheckBox), /* tp_basicsize */
};

struct FGetSets_CheckBox
{
	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_CheckedStateDelegate()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UCheckBox::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("CheckedStateDelegate")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetCheckedStateDelegate(FUPyWrapperCheckBox* InSelf, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_CheckedStateDelegate(), "CheckedStateDelegate");
	}

	static int SetCheckedStateDelegate(FUPyWrapperCheckBox* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_CheckedStateDelegate(), "CheckedStateDelegate");
	}

	static PyObject* GetHorizontalAlignment(FUPyWrapperCheckBox* InSelf, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return UPyConversion::PythonizeEnumEntry((int64)InSelf->ValuePtr()->HorizontalAlignment, StaticEnum<EHorizontalAlignment>());
	}

	static int SetHorizontalAlignment(FUPyWrapperCheckBox* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return -1;
		}
		if (UPyConversion::NativizeEnumEntry(InValue, StaticEnum<EHorizontalAlignment>(), InSelf->ValuePtr()->HorizontalAlignment))
		{
			return 0;
		}
		UPyUtil::SetPythonError(PyExc_TypeError, TEXT("CheckBox::HorizontalAlignment"), TEXT("value is not numeric"));
		return -1;
	}

	static UPyGenUtil::FGeneratedWrappedProperty& GetPropertyDef_OnCheckStateChanged()
	{
		static bool bInitialized = false;
		static UPyGenUtil::FGeneratedWrappedProperty Property;
		if (!bInitialized)
		{
			if (const UClass* Class = UCheckBox::StaticClass())
			{
				if (const FProperty* FoundProperty = Class->FindPropertyByName(TEXT("OnCheckStateChanged")))
				{
					Property.SetProperty(FoundProperty);
				}
			}
			bInitialized = true;
		}
		return Property;
	}

	static PyObject* GetOnCheckStateChanged(FUPyWrapperCheckBox* InSelf, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		return FUPyWrapperObject::GetPropertyValue(InSelf, GetPropertyDef_OnCheckStateChanged(), "OnCheckStateChanged");
	}

	static int SetOnCheckStateChanged(FUPyWrapperCheckBox* InSelf, PyObject* InValue, void* InClosure)
	{
		if (!FUPyWrapperCheckBox::ValidateInternalState(InSelf))
		{
			return -1;
		}
		return FUPyWrapperObject::SetPropertyValue(InSelf, InValue, GetPropertyDef_OnCheckStateChanged(), "OnCheckStateChanged");
	}

};


static PyGetSetDef FUPyWrapperCheckBoxGetSets[] = {
	{ UPyCStrCast("CheckedStateDelegate"), (getter)&FGetSets_CheckBox::GetCheckedStateDelegate, (setter)&FGetSets_CheckBox::SetCheckedStateDelegate, nullptr, nullptr },
	{ UPyCStrCast("HorizontalAlignment"), (getter)&FGetSets_CheckBox::GetHorizontalAlignment, (setter)&FGetSets_CheckBox::SetHorizontalAlignment, nullptr, nullptr },
	{ UPyCStrCast("OnCheckStateChanged"), (getter)&FGetSets_CheckBox::GetOnCheckStateChanged, (setter)&FGetSets_CheckBox::SetOnCheckStateChanged, nullptr, nullptr },
	{ nullptr }
};



struct FMethods_CheckBox
{
	static PyObject* CallGetCheckedState(FUPyWrapperCheckBox* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const auto Result = InSelf->ValuePtr()->GetCheckedState();
		return UPyConversion::PythonizeEnumEntry((int64)Result, StaticEnum<ECheckBoxState>());
	}

	static PyObject* CallIsChecked(FUPyWrapperCheckBox* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsChecked();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallIsPressed(FUPyWrapperCheckBox* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		const bool bResult = InSelf->ValuePtr()->IsPressed();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallSetCheckedState(FUPyWrapperCheckBox* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		ECheckBoxState Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<ECheckBoxState>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("CheckBox::SetCheckedState"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetCheckedState(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetClickMethod(FUPyWrapperCheckBox* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		EButtonClickMethod::Type Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<EButtonClickMethod::Type>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("CheckBox::SetClickMethod"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetClickMethod(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetIsChecked(FUPyWrapperCheckBox* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		bool Arg0 = false;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("CheckBox::SetIsChecked"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetIsChecked(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetPressMethod(FUPyWrapperCheckBox* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		EButtonPressMethod::Type Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<EButtonPressMethod::Type>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("CheckBox::SetPressMethod"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetPressMethod(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetTouchMethod(FUPyWrapperCheckBox* InSelf, PyObject* InArg)
	{
		if (!InSelf->ValidateInternalState(InSelf))
		{
			return nullptr;
		}
		EButtonTouchMethod::Type Arg0;
		if (!UPyConversion::NativizeEnumEntry(InArg, StaticEnum<EButtonTouchMethod::Type>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("CheckBox::SetTouchMethod"), TEXT("invalid argument"));
			return nullptr;
		}

		InSelf->ValuePtr()->SetTouchMethod(Arg0);
		Py_RETURN_NONE;
	}

};


static PyMethodDef FUPyWrapperCheckBoxPyMethodDefs[] = {
	{ "GetCheckedState", UPyCFunctionCast(&FMethods_CheckBox::CallGetCheckedState), METH_NOARGS, nullptr },
	{ "IsChecked", UPyCFunctionCast(&FMethods_CheckBox::CallIsChecked), METH_NOARGS, nullptr },
	{ "IsPressed", UPyCFunctionCast(&FMethods_CheckBox::CallIsPressed), METH_NOARGS, nullptr },
	{ "SetCheckedState", UPyCFunctionCast(&FMethods_CheckBox::CallSetCheckedState), METH_O, nullptr },
	{ "SetClickMethod", UPyCFunctionCast(&FMethods_CheckBox::CallSetClickMethod), METH_O, nullptr },
	{ "SetIsChecked", UPyCFunctionCast(&FMethods_CheckBox::CallSetIsChecked), METH_O, nullptr },
	{ "SetPressMethod", UPyCFunctionCast(&FMethods_CheckBox::CallSetPressMethod), METH_O, nullptr },
	{ "SetTouchMethod", UPyCFunctionCast(&FMethods_CheckBox::CallSetTouchMethod), METH_O, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperCheckBox(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperCheckBoxType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperCheckBoxPyMethodDefs;
	PyType->tp_getset = FUPyWrapperCheckBoxGetSets;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperCheckBox(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UCheckBox::StaticClass(), DoInitWrapperCheckBox);
}

FUPyWrapperCheckBox* UPyIsCheckBox(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperCheckBoxType))
	{
		return (FUPyWrapperCheckBox*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UCheckBox*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperCheckBox* PyCheckBox = UPyIsCheckBox(PyObj))
		{
			if (!FUPyWrapperObject::ValidateInternalState(PyCheckBox))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyCheckBox->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UCheckBox'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
