
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/UMG/Class/UPyWrapperWidgetLayoutLibrary.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "UObject/NoExportTypes.h"
#include "UObject/Object.h"
#include "GameFramework/PlayerController.h"
#include "Layout/Geometry.h"
#include "Components/Widget.h"
#include "Components/BorderSlot.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/GridSlot.h"
#include "Components/HorizontalBoxSlot.h"
#include "Components/OverlaySlot.h"
#include "Components/SafeZoneSlot.h"
#include "Components/ScaleBoxSlot.h"
#include "Components/ScrollBoxSlot.h"
#include "Components/SizeBoxSlot.h"
#include "Components/StackBoxSlot.h"
#include "Components/UniformGridSlot.h"
#include "Components/VerticalBoxSlot.h"
#include "Components/WidgetSwitcherSlot.h"
#include "Components/WrapBoxSlot.h"


PyTypeObject UPyWrapperWidgetLayoutLibraryType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"WidgetLayoutLibrary", /* tp_name */
	sizeof(FUPyWrapperWidgetLayoutLibrary), /* tp_basicsize */
};




struct FMethods_WidgetLayoutLibrary
{
	static PyObject* CallGetMousePositionOnPlatform(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = UWidgetLayoutLibrary::GetMousePositionOnPlatform();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetMousePositionOnViewport(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetMousePositionOnViewport"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::GetMousePositionOnViewport(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetMousePositionScaledByDPI(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetMousePositionScaledByDPI"), TEXT("invalid argument"));
			return nullptr;
		}

		float OutParam0 = 0.0f;
		float OutParam1 = 0.0f;
		// Call the method
		const bool ReturnValue = UWidgetLayoutLibrary::GetMousePositionScaledByDPI(Arg0, OutParam0, OutParam1);

		// Build return tuple with 3 values
		PyObject* ReturnTuple = PyTuple_New(3);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, PyBool_FromLong(ReturnValue ? 1 : 0));
		// Add output parameter 'LocationX' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::Pythonize(OutParam0));
		// Add output parameter 'LocationY' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 2, UPyConversion::Pythonize(OutParam1));

		return ReturnTuple;
	}

	static PyObject* CallGetPlayerScreenWidgetGeometry(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetPlayerScreenWidgetGeometry"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::GetPlayerScreenWidgetGeometry(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetViewportScale(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetViewportScale"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::GetViewportScale(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetViewportSize(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetViewportSize"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::GetViewportSize(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetViewportWidgetGeometry(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::GetViewportWidgetGeometry"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::GetViewportWidgetGeometry(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallProjectWorldLocationToWidgetPosition(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		bool Arg2 = false;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition"), TEXT("invalid argument"));
			return nullptr;
		}

		FVector2D OutParam0;
		// Call the method
		const bool ReturnValue = UWidgetLayoutLibrary::ProjectWorldLocationToWidgetPosition(Arg0, Arg1, OutParam0, Arg2);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, PyBool_FromLong(ReturnValue ? 1 : 0));
		// Add output parameter 'ScreenPosition' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(OutParam0));

		return ReturnTuple;
	}

	static PyObject* CallRemoveAllWidgets(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::RemoveAllWidgets"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetLayoutLibrary::RemoveAllWidgets(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSlotAsBorderSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsBorderSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsBorderSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsCanvasSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsCanvasSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsCanvasSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsGridSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsGridSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsGridSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsHorizontalBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsHorizontalBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsHorizontalBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsOverlaySlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsOverlaySlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsOverlaySlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsSafeBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsSafeBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsSafeBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsScaleBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsScaleBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsScaleBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsScrollBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsScrollBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsScrollBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsSizeBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsSizeBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsSizeBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsStackBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsStackBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsStackBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsUniformGridSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsUniformGridSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsUniformGridSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsVerticalBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsVerticalBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsVerticalBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsWidgetSwitcherSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsWidgetSwitcherSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsWidgetSwitcherSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallSlotAsWrapBoxSlot(FUPyWrapperWidgetLayoutLibrary* InSelf, PyObject* InArg)
	{
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetLayoutLibrary::SlotAsWrapBoxSlot"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetLayoutLibrary::SlotAsWrapBoxSlot(Arg0);
		return UPyConversion::Pythonize(Result);
	}

};


static PyMethodDef FUPyWrapperWidgetLayoutLibraryPyMethodDefs[] = {
	{ "GetMousePositionOnPlatform", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetMousePositionOnPlatform), METH_NOARGS | METH_STATIC, nullptr },
	{ "GetMousePositionOnViewport", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetMousePositionOnViewport), METH_O | METH_STATIC, nullptr },
	{ "GetMousePositionScaledByDPI", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetMousePositionScaledByDPI), METH_O | METH_STATIC, nullptr },
	{ "GetPlayerScreenWidgetGeometry", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetPlayerScreenWidgetGeometry), METH_O | METH_STATIC, nullptr },
	{ "GetViewportScale", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetViewportScale), METH_O | METH_STATIC, nullptr },
	{ "GetViewportSize", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetViewportSize), METH_O | METH_STATIC, nullptr },
	{ "GetViewportWidgetGeometry", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallGetViewportWidgetGeometry), METH_O | METH_STATIC, nullptr },
	{ "ProjectWorldLocationToWidgetPosition", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallProjectWorldLocationToWidgetPosition), METH_VARARGS | METH_STATIC, nullptr },
	{ "RemoveAllWidgets", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallRemoveAllWidgets), METH_O | METH_STATIC, nullptr },
	{ "SlotAsBorderSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsBorderSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsCanvasSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsCanvasSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsGridSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsGridSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsHorizontalBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsHorizontalBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsOverlaySlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsOverlaySlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsSafeBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsSafeBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsScaleBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsScaleBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsScrollBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsScrollBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsSizeBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsSizeBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsStackBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsStackBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsUniformGridSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsUniformGridSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsVerticalBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsVerticalBoxSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsWidgetSwitcherSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsWidgetSwitcherSlot), METH_O | METH_STATIC, nullptr },
	{ "SlotAsWrapBoxSlot", UPyCFunctionCast(&FMethods_WidgetLayoutLibrary::CallSlotAsWrapBoxSlot), METH_O | METH_STATIC, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperWidgetLayoutLibrary(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperWidgetLayoutLibraryType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperWidgetLayoutLibraryPyMethodDefs;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperWidgetLayoutLibrary(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UWidgetLayoutLibrary::StaticClass(), DoInitWrapperWidgetLayoutLibrary);
}

FUPyWrapperWidgetLayoutLibrary* UPyIsWidgetLayoutLibrary(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperWidgetLayoutLibraryType))
	{
		return (FUPyWrapperWidgetLayoutLibrary*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UWidgetLayoutLibrary*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperWidgetLayoutLibrary* PyWidgetLayoutLibrary = UPyIsWidgetLayoutLibrary(PyObj))
		{
			if (!FUPyWrapperObject::ValidateInternalState(PyWidgetLayoutLibrary))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyWidgetLayoutLibrary->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UWidgetLayoutLibrary'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
