// Copyright Epic Games, Inc. All Rights Reserved.

// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Blueprint/GameViewportSubsystem.h"


/** Python type for FUPyWrapperGameViewportSubsystem */
extern PyTypeObject UPyWrapperGameViewportSubsystemType;

/** Initialize the UPyWrapperGameViewportSubsystemType types and add them to the given Python module */
void InitializeUPyWrapperGameViewportSubsystem(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperGameViewportSubsystem: public FUPyWrapperObjectBase 
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperGameViewportSubsystemType;
	}

	UNREALPYTHON_API UGameViewportSubsystem* ValuePtr() const
	{
		return Cast<UGameViewportSubsystem>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperGameViewportSubsystem* UPyIsGameViewportSubsystem(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UGameViewportSubsystem*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
