
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/Image.h"


/** Python type for FUPyWrapperImage */
extern PyTypeObject UPyWrapperImageType;

/** Initialize the UPyWrapperImageType types and add them to the given Python module */
void InitializeUPyWrapperImage(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperImage: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperImageType;
	}

	UNREALPYTHON_API UImage* ValuePtr() const
	{
		return Cast<UImage>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperImage* UPyIsImage(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UImage*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
