
// This file is automatically generated. Do not edit manually.

#pragma once

#include "Wrapper/UPyWrapperObject.h"
#include "Utils/UPyGenUtil.h"
#include "Components/ScrollBox.h"


/** Python type for FUPyWrapperScrollBox */
extern PyTypeObject UPyWrapperScrollBoxType;

/** Initialize the UPyWrapperScrollBoxType types and add them to the given Python module */
void InitializeUPyWrapperScrollBox(UPyGenUtil::FNativePythonModule& ModuleInfo);

class FUPyWrapperScrollBox: public FUPyWrapperObject
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &UPyWrapperScrollBoxType;
	}

	UNREALPYTHON_API UScrollBox* ValuePtr() const
	{
		return Cast<UScrollBox>(ObjectInstance);
	}
};

UNREALPYTHON_API FUPyWrapperScrollBox* UPyIsScrollBox(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult Nativize(PyObject* PyObj, UScrollBox*& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
