
// This file is automatically generated. Do not edit manually.

#include "Wrapper/AutoGen/UMG/Class/UPyWrapperWidgetBlueprintLibrary.h"
#include "Wrapper/UPyWrapperTypeRegistry.h"
#include "Wrapper/UPyWrapperTypeFactory.h"
#include "Utils/UPyUtil.h"
#include "Components/SlateWrapperTypes.h"
#include "Components/Widget.h"
#include "UObject/Object.h"
#include "UObject/Class.h"
#include "GameFramework/PlayerController.h"
#include "Blueprint/UserWidget.h"
#include "Blueprint/DragDropOperation.h"
#include "InputCoreTypes.h"
#include "Input/Events.h"
#include "UObject/NoExportTypes.h"
#include "Slate/SlateBrushAsset.h"
#include "Engine/Font.h"
#include "Styling/SlateBrush.h"
#include "Materials/MaterialInterface.h"
#include "Engine/Texture2D.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Rendering/RenderingCommon.h"
#include "Engine/EngineBaseTypes.h"
#include "Slate/SGameLayerManager.h"


PyTypeObject UPyWrapperWidgetBlueprintLibraryType = {
	PyVarObject_HEAD_INIT(nullptr, 0)
	"WidgetBlueprintLibrary", /* tp_name */
	sizeof(FUPyWrapperWidgetBlueprintLibrary), /* tp_basicsize */
};




struct FMethods_WidgetBlueprintLibrary
{
	static PyObject* CallCancelDragDrop(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		UWidgetBlueprintLibrary::CancelDragDrop();
		Py_RETURN_NONE;
	}

	static PyObject* CallCaptureMouse(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::CaptureMouse"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::CaptureMouse"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::CaptureMouse(Arg0, Arg1);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallClearUserFocus(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::ClearUserFocus"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		bool Arg1 = false;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::ClearUserFocus"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::ClearUserFocus(Arg0, Arg1);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallCreate(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::Create"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg1 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg1, Arg1, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::Create"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		APlayerController* Arg2 = nullptr;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::Create"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::Create(Arg0, Arg1, Arg2);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallCreateDragDropOperation(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		UClass* Arg0 = nullptr;
		if (!UPyConversion::NativizeClass(InArg, Arg0, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::CreateDragDropOperation"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::CreateDragDropOperation(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallDetectDrag(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDrag"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDrag"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FKey Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDrag"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::DetectDrag(Arg0, Arg1, Arg2);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallDetectDragIfPressed(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPointerEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDragIfPressed"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDragIfPressed"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FKey Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DetectDragIfPressed"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::DetectDragIfPressed(Arg0, Arg1, Arg2);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallDismissAllMenus(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		UWidgetBlueprintLibrary::DismissAllMenus();
		Py_RETURN_NONE;
	}

	static PyObject* CallDrawBox(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPaintContext Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawBox"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawBox"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawBox"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		USlateBrushAsset* Arg3 = nullptr;
		if (!UPyConversion::Nativize(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawBox"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = (ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		FLinearColor Arg4 = FLinearColor(1.000000f, 1.000000f, 1.000000f, 1.000000f);
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::NativizeStructInstance(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawBox"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::DrawBox(Arg0, Arg1, Arg2, Arg3, Arg4);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallDrawLine(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPaintContext Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = (ArgCount > 3) ? PyTuple_GetItem(InArgs, 3) : nullptr;
		FLinearColor Arg3 = FLinearColor(1.000000f, 1.000000f, 1.000000f, 1.000000f);
		if (PyArg3 != nullptr)
		{
			if (!UPyConversion::NativizeStructInstance(PyArg3, Arg3))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg4 = (PyArg3 && ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		bool Arg4 = true;
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg5 = (PyArg4 && ArgCount > 5) ? PyTuple_GetItem(InArgs, 5) : nullptr;
		float Arg5 = 1.000000f;
		if (PyArg5 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg5, Arg5))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLine"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::DrawLine(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallDrawLines(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPaintContext Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		TArray<FVector2D> Arg1;
		if (!PySequence_Check(PyArg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
			return nullptr;
		}
		Py_ssize_t Len_Arg1 = PySequence_Size(PyArg1);
		int32 ElementCount_Arg1 = 0;
		if (UPyUtil::ValidateContainerLenValue(Len_Arg1, ElementCount_Arg1, TEXT("Array")) != 0)
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
			return nullptr;
		}
		Arg1.SetNum(ElementCount_Arg1);
		for (int32 i = 0; i < ElementCount_Arg1; ++i)
		{
			PyObject* Item = PySequence_GetItem(PyArg1, i);
			if (!Item)
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
				return nullptr;

			}
			if (!UPyConversion::NativizeStructInstance(Item, Arg1[i]))
			{
				Py_DECREF(Item);
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
				return nullptr;

			}
			Py_DECREF(Item);
		}

		PyObject* PyArg2 = (ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		FLinearColor Arg2 = FLinearColor(1.000000f, 1.000000f, 1.000000f, 1.000000f);
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg3 = (PyArg2 && ArgCount > 3) ? PyTuple_GetItem(InArgs, 3) : nullptr;
		bool Arg3 = true;
		if (PyArg3 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg3, Arg3))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg4 = (PyArg3 && ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		float Arg4 = 1.000000f;
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawLines"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::DrawLines(Arg0, Arg1, Arg2, Arg3, Arg4);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallDrawSpline(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPaintContext Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg3;
		if (!UPyConversion::NativizeStructInstance(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = PyTuple_GetItem(InArgs, 4);
		if (PyArg4 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg4;
		if (!UPyConversion::NativizeStructInstance(PyArg4, Arg4))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg5 = (ArgCount > 5) ? PyTuple_GetItem(InArgs, 5) : nullptr;
		FLinearColor Arg5 = FLinearColor(1.000000f, 1.000000f, 1.000000f, 1.000000f);
		if (PyArg5 != nullptr)
		{
			if (!UPyConversion::NativizeStructInstance(PyArg5, Arg5))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg6 = (PyArg5 && ArgCount > 6) ? PyTuple_GetItem(InArgs, 6) : nullptr;
		float Arg6 = 1.000000f;
		if (PyArg6 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg6, Arg6))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawSpline"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::DrawSpline(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallDrawTextFormatted(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FPaintContext Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FText Arg1;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg2;
		if (!UPyConversion::NativizeStructInstance(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		UFont* Arg3 = nullptr;
		if (!UPyConversion::Nativize(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = (ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		float Arg4 = 16.000000f;
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg5 = (PyArg4 && ArgCount > 5) ? PyTuple_GetItem(InArgs, 5) : nullptr;
		FName Arg5 = TEXT("Regular");
		if (PyArg5 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg5, Arg5))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg6 = (PyArg5 && ArgCount > 6) ? PyTuple_GetItem(InArgs, 6) : nullptr;
		FLinearColor Arg6 = FLinearColor(1.000000f, 1.000000f, 1.000000f, 1.000000f);
		if (PyArg6 != nullptr)
		{
			if (!UPyConversion::NativizeStructInstance(PyArg6, Arg6))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::DrawTextFormatted"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::DrawTextFormatted(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallEndDragDrop(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::EndDragDrop"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::EndDragDrop(Arg0);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallGetAllWidgetsOfClass(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsOfClass"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg1 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg1, Arg1, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsOfClass"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = (ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		bool Arg2 = true;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsOfClass"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		TArray<UUserWidget*> OutParam0;
		UWidgetBlueprintLibrary::GetAllWidgetsOfClass(Arg0, OutParam0, Arg1, Arg2);
		PyObject* PyList = PyList_New(OutParam0.Num());
		for (int32 i = 0; i < OutParam0.Num(); ++i)
		{
			PyObject* PyItem = UPyConversion::Pythonize(OutParam0[i]);
			PyList_SET_ITEM(PyList, i, PyItem);
		}
		return PyList;
	}

	static PyObject* CallGetAllWidgetsWithInterface(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsWithInterface"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UClass* Arg1 = nullptr;
		if (!UPyConversion::NativizeClass(PyArg1, Arg1, nullptr))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsWithInterface"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		bool Arg2 = false;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetAllWidgetsWithInterface"), TEXT("invalid argument"));
			return nullptr;
		}

		TArray<UUserWidget*> OutParam0;
		UWidgetBlueprintLibrary::GetAllWidgetsWithInterface(Arg0, OutParam0, Arg1, Arg2);
		PyObject* PyList = PyList_New(OutParam0.Num());
		for (int32 i = 0; i < OutParam0.Num(); ++i)
		{
			PyObject* PyItem = UPyConversion::Pythonize(OutParam0[i]);
			PyList_SET_ITEM(PyList, i, PyItem);
		}
		return PyList;
	}

	static PyObject* CallGetBrushResource(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetBrushResource"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetBrushResource(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetBrushResourceAsMaterial(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetBrushResourceAsMaterial"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetBrushResourceAsMaterial(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetBrushResourceAsTexture2D(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetBrushResourceAsTexture2D"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetBrushResourceAsTexture2D(Arg0);
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetDragDroppingContent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = UWidgetBlueprintLibrary::GetDragDroppingContent();
		return UPyConversion::Pythonize(Result);
	}

	static PyObject* CallGetDynamicMaterial(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetDynamicMaterial"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::GetDynamicMaterial(Arg0);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::Pythonize(ReturnValue));
		// Add output parameter 'Brush' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallGetInputEventFromCharacterEvent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FCharacterEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetInputEventFromCharacterEvent"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetInputEventFromCharacterEvent(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetInputEventFromKeyEvent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FKeyEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetInputEventFromKeyEvent"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetInputEventFromKeyEvent(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetInputEventFromNavigationEvent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FNavigationEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetInputEventFromNavigationEvent"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetInputEventFromNavigationEvent(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetInputEventFromPointerEvent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FPointerEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetInputEventFromPointerEvent"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetInputEventFromPointerEvent(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetKeyEventFromAnalogInputEvent(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FAnalogInputEvent Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetKeyEventFromAnalogInputEvent"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::GetKeyEventFromAnalogInputEvent(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallGetSafeZonePadding(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::GetSafeZonePadding"), TEXT("invalid argument"));
			return nullptr;
		}

		FVector4 OutParam0;
		FVector2D OutParam1;
		FVector4 OutParam2;
		// Call the method
		UWidgetBlueprintLibrary::GetSafeZonePadding(Arg0, OutParam0, OutParam1, OutParam2);

		// Build return tuple with 3 values
		PyObject* ReturnTuple = PyTuple_New(3);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add output parameter 'SafePadding' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(OutParam0));
		// Add output parameter 'SafePaddingScale' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(OutParam1));
		// Add output parameter 'SpillOverPadding' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 2, UPyConversion::PythonizeStructInstance(OutParam2));

		return ReturnTuple;
	}

	static PyObject* CallHandled(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = UWidgetBlueprintLibrary::Handled();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallIsDragDropping(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const bool bResult = UWidgetBlueprintLibrary::IsDragDropping();
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallLockMouse(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::LockMouse"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::LockMouse"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::LockMouse(Arg0, Arg1);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallMakeBrushFromAsset(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		USlateBrushAsset* Arg0 = nullptr;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromAsset"), TEXT("invalid argument"));
			return nullptr;
		}

		const auto Result = UWidgetBlueprintLibrary::MakeBrushFromAsset(Arg0);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallMakeBrushFromMaterial(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UMaterialInterface* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromMaterial"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		int32 Arg1 = 32;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromMaterial"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg2 = (PyArg1 && ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		int32 Arg2 = 32;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromMaterial"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		const auto Result = UWidgetBlueprintLibrary::MakeBrushFromMaterial(Arg0, Arg1, Arg2);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallMakeBrushFromTexture(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UTexture2D* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromTexture"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		int32 Arg1 = 0;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromTexture"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg2 = (PyArg1 && ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		int32 Arg2 = 0;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::MakeBrushFromTexture"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		const auto Result = UWidgetBlueprintLibrary::MakeBrushFromTexture(Arg0, Arg1, Arg2);
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallNoResourceBrush(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = UWidgetBlueprintLibrary::NoResourceBrush();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallReleaseMouseCapture(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::ReleaseMouseCapture"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::ReleaseMouseCapture(Arg0);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallRestorePreviousWindowTitleBarState(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		UWidgetBlueprintLibrary::RestorePreviousWindowTitleBarState();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetBrushResourceToMaterial(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetBrushResourceToMaterial"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UMaterialInterface* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetBrushResourceToMaterial"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetBlueprintLibrary::SetBrushResourceToMaterial(Arg0, Arg1);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallSetBrushResourceToTexture(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FSlateBrush Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetBrushResourceToTexture"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UTexture2D* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetBrushResourceToTexture"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetBlueprintLibrary::SetBrushResourceToTexture(Arg0, Arg1);
		return UPyConversion::PythonizeStructInstance(Arg0);
	}

	static PyObject* CallSetColorVisionDeficiencyType(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		EColorVisionDeficiency Arg0;
		if (!UPyConversion::NativizeEnumEntry(PyArg0, StaticEnum<EColorVisionDeficiency>(), Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetColorVisionDeficiencyType"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		float Arg1 = 0.0f;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetColorVisionDeficiencyType"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		bool Arg2 = false;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetColorVisionDeficiencyType"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		bool Arg3 = false;
		if (!UPyConversion::Nativize(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetColorVisionDeficiencyType"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetBlueprintLibrary::SetColorVisionDeficiencyType(Arg0, Arg1, Arg2, Arg3);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetFocusToGameViewport(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		UWidgetBlueprintLibrary::SetFocusToGameViewport();
		Py_RETURN_NONE;
	}

	static PyObject* CallSetHardwareCursor(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UObject* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetHardwareCursor"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		EMouseCursor::Type Arg1;
		if (!UPyConversion::NativizeEnumEntry(PyArg1, StaticEnum<EMouseCursor::Type>(), Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetHardwareCursor"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		FName Arg2;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetHardwareCursor"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg3;
		if (!UPyConversion::NativizeStructInstance(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetHardwareCursor"), TEXT("invalid argument"));
			return nullptr;
		}

		const bool bResult = UWidgetBlueprintLibrary::SetHardwareCursor(Arg0, Arg1, Arg2, Arg3);
		return PyBool_FromLong(bResult ? 1 : 0);
	}

	static PyObject* CallSetInputMode_GameAndUIEx(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameAndUIEx"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		UWidget* Arg1 = nullptr;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameAndUIEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg2 = (PyArg1 && ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		EMouseLockMode Arg2 = EMouseLockMode::DoNotLock;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::NativizeEnumEntry(PyArg2, StaticEnum<EMouseLockMode>(), Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameAndUIEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg3 = (PyArg2 && ArgCount > 3) ? PyTuple_GetItem(InArgs, 3) : nullptr;
		bool Arg3 = true;
		if (PyArg3 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg3, Arg3))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameAndUIEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg4 = (PyArg3 && ArgCount > 4) ? PyTuple_GetItem(InArgs, 4) : nullptr;
		bool Arg4 = false;
		if (PyArg4 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg4, Arg4))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameAndUIEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::SetInputMode_GameAndUIEx(Arg0, Arg1, Arg2, Arg3, Arg4);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetInputMode_GameOnly(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameOnly"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		bool Arg1 = false;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_GameOnly"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::SetInputMode_GameOnly(Arg0, Arg1);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetInputMode_UIOnlyEx(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		APlayerController* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_UIOnlyEx"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = (ArgCount > 1) ? PyTuple_GetItem(InArgs, 1) : nullptr;
		UWidget* Arg1 = nullptr;
		if (PyArg1 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg1, Arg1))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_UIOnlyEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg2 = (PyArg1 && ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		EMouseLockMode Arg2 = EMouseLockMode::DoNotLock;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::NativizeEnumEntry(PyArg2, StaticEnum<EMouseLockMode>(), Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_UIOnlyEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		PyObject* PyArg3 = (PyArg2 && ArgCount > 3) ? PyTuple_GetItem(InArgs, 3) : nullptr;
		bool Arg3 = false;
		if (PyArg3 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg3, Arg3))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetInputMode_UIOnlyEx"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		UWidgetBlueprintLibrary::SetInputMode_UIOnlyEx(Arg0, Arg1, Arg2, Arg3);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetMousePosition(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetMousePosition"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		FVector2D Arg1;
		if (!UPyConversion::NativizeStructInstance(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetMousePosition"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::SetMousePosition(Arg0, Arg1);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallSetUserFocus(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		Py_ssize_t ArgCount = PyTuple_GET_SIZE(InArgs);
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetUserFocus"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg1 = nullptr;
		if (!UPyConversion::Nativize(PyArg1, Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetUserFocus"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = (ArgCount > 2) ? PyTuple_GetItem(InArgs, 2) : nullptr;
		bool Arg2 = false;
		if (PyArg2 != nullptr)
		{
			if (!UPyConversion::Nativize(PyArg2, Arg2))
			{
				UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetUserFocus"), TEXT("invalid argument"));
				return nullptr;
			}
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::SetUserFocus(Arg0, Arg1, Arg2);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

	static PyObject* CallSetWindowTitleBarCloseButtonActive(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		bool Arg0 = false;
		if (!UPyConversion::Nativize(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarCloseButtonActive"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetBlueprintLibrary::SetWindowTitleBarCloseButtonActive(Arg0);
		Py_RETURN_NONE;
	}

	static PyObject* CallSetWindowTitleBarOnCloseClickedDelegate(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InArg))
	{
		UPyUtil::SetPythonError(PyExc_NotImplementedError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarOnCloseClickedDelegate"), TEXT("method binding has not been generated yet"));
		return nullptr;
	}

	static PyObject* CallSetWindowTitleBarState(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArgs)
	{
		PyObject* PyArg0 = PyTuple_GetItem(InArgs, 0);
		if (PyArg0 == nullptr)
		{
			return nullptr;
		}
		UWidget* Arg0 = nullptr;
		if (!UPyConversion::Nativize(PyArg0, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarState"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg1 = PyTuple_GetItem(InArgs, 1);
		if (PyArg1 == nullptr)
		{
			return nullptr;
		}
		EWindowTitleBarMode Arg1;
		if (!UPyConversion::NativizeEnumEntry(PyArg1, StaticEnum<EWindowTitleBarMode>(), Arg1))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarState"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg2 = PyTuple_GetItem(InArgs, 2);
		if (PyArg2 == nullptr)
		{
			return nullptr;
		}
		bool Arg2 = false;
		if (!UPyConversion::Nativize(PyArg2, Arg2))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarState"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg3 = PyTuple_GetItem(InArgs, 3);
		if (PyArg3 == nullptr)
		{
			return nullptr;
		}
		bool Arg3 = false;
		if (!UPyConversion::Nativize(PyArg3, Arg3))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarState"), TEXT("invalid argument"));
			return nullptr;
		}

		PyObject* PyArg4 = PyTuple_GetItem(InArgs, 4);
		if (PyArg4 == nullptr)
		{
			return nullptr;
		}
		bool Arg4 = false;
		if (!UPyConversion::Nativize(PyArg4, Arg4))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::SetWindowTitleBarState"), TEXT("invalid argument"));
			return nullptr;
		}

		UWidgetBlueprintLibrary::SetWindowTitleBarState(Arg0, Arg1, Arg2, Arg3, Arg4);
		Py_RETURN_NONE;
	}

	static PyObject* CallUnhandled(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* Py_UNUSED(InUnused))
	{
		const auto Result = UWidgetBlueprintLibrary::Unhandled();
		return UPyConversion::PythonizeStructInstance(Result);
	}

	static PyObject* CallUnlockMouse(FUPyWrapperWidgetBlueprintLibrary* InSelf, PyObject* InArg)
	{
		FEventReply Arg0;
		if (!UPyConversion::NativizeStructInstance(InArg, Arg0))
		{
			UPyUtil::SetPythonError(PyExc_RuntimeError, TEXT("WidgetBlueprintLibrary::UnlockMouse"), TEXT("invalid argument"));
			return nullptr;
		}

		// Call the method
		const auto ReturnValue = UWidgetBlueprintLibrary::UnlockMouse(Arg0);

		// Build return tuple with 2 values
		PyObject* ReturnTuple = PyTuple_New(2);
		if (ReturnTuple == nullptr)
		{
			return nullptr;
		}

		// Add return value to tuple
		PyTuple_SET_ITEM(ReturnTuple, 0, UPyConversion::PythonizeStructInstance(ReturnValue));
		// Add output parameter 'Reply' to tuple
		PyTuple_SET_ITEM(ReturnTuple, 1, UPyConversion::PythonizeStructInstance(Arg0));

		return ReturnTuple;
	}

};


static PyMethodDef FUPyWrapperWidgetBlueprintLibraryPyMethodDefs[] = {
	{ "CancelDragDrop", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallCancelDragDrop), METH_NOARGS | METH_STATIC, nullptr },
	{ "CaptureMouse", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallCaptureMouse), METH_VARARGS | METH_STATIC, nullptr },
	{ "ClearUserFocus", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallClearUserFocus), METH_VARARGS | METH_STATIC, nullptr },
	{ "Create", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallCreate), METH_VARARGS | METH_STATIC, nullptr },
	{ "CreateDragDropOperation", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallCreateDragDropOperation), METH_O | METH_STATIC, nullptr },
	{ "DetectDrag", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDetectDrag), METH_VARARGS | METH_STATIC, nullptr },
	{ "DetectDragIfPressed", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDetectDragIfPressed), METH_VARARGS | METH_STATIC, nullptr },
	{ "DismissAllMenus", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDismissAllMenus), METH_NOARGS | METH_STATIC, nullptr },
	{ "DrawBox", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDrawBox), METH_VARARGS | METH_STATIC, nullptr },
	{ "DrawLine", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDrawLine), METH_VARARGS | METH_STATIC, nullptr },
	{ "DrawLines", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDrawLines), METH_VARARGS | METH_STATIC, nullptr },
	{ "DrawSpline", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDrawSpline), METH_VARARGS | METH_STATIC, nullptr },
	{ "DrawTextFormatted", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallDrawTextFormatted), METH_VARARGS | METH_STATIC, nullptr },
	{ "EndDragDrop", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallEndDragDrop), METH_O | METH_STATIC, nullptr },
	{ "GetAllWidgetsOfClass", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetAllWidgetsOfClass), METH_VARARGS | METH_STATIC, nullptr },
	{ "GetAllWidgetsWithInterface", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetAllWidgetsWithInterface), METH_VARARGS | METH_STATIC, nullptr },
	{ "GetBrushResource", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetBrushResource), METH_O | METH_STATIC, nullptr },
	{ "GetBrushResourceAsMaterial", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetBrushResourceAsMaterial), METH_O | METH_STATIC, nullptr },
	{ "GetBrushResourceAsTexture2D", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetBrushResourceAsTexture2D), METH_O | METH_STATIC, nullptr },
	{ "GetDragDroppingContent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetDragDroppingContent), METH_NOARGS | METH_STATIC, nullptr },
	{ "GetDynamicMaterial", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetDynamicMaterial), METH_O | METH_STATIC, nullptr },
	{ "GetInputEventFromCharacterEvent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetInputEventFromCharacterEvent), METH_O | METH_STATIC, nullptr },
	{ "GetInputEventFromKeyEvent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetInputEventFromKeyEvent), METH_O | METH_STATIC, nullptr },
	{ "GetInputEventFromNavigationEvent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetInputEventFromNavigationEvent), METH_O | METH_STATIC, nullptr },
	{ "GetInputEventFromPointerEvent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetInputEventFromPointerEvent), METH_O | METH_STATIC, nullptr },
	{ "GetKeyEventFromAnalogInputEvent", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetKeyEventFromAnalogInputEvent), METH_O | METH_STATIC, nullptr },
	{ "GetSafeZonePadding", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallGetSafeZonePadding), METH_O | METH_STATIC, nullptr },
	{ "Handled", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallHandled), METH_NOARGS | METH_STATIC, nullptr },
	{ "IsDragDropping", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallIsDragDropping), METH_NOARGS | METH_STATIC, nullptr },
	{ "LockMouse", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallLockMouse), METH_VARARGS | METH_STATIC, nullptr },
	{ "MakeBrushFromAsset", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallMakeBrushFromAsset), METH_O | METH_STATIC, nullptr },
	{ "MakeBrushFromMaterial", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallMakeBrushFromMaterial), METH_VARARGS | METH_STATIC, nullptr },
	{ "MakeBrushFromTexture", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallMakeBrushFromTexture), METH_VARARGS | METH_STATIC, nullptr },
	{ "NoResourceBrush", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallNoResourceBrush), METH_NOARGS | METH_STATIC, nullptr },
	{ "ReleaseMouseCapture", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallReleaseMouseCapture), METH_O | METH_STATIC, nullptr },
	{ "RestorePreviousWindowTitleBarState", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallRestorePreviousWindowTitleBarState), METH_NOARGS | METH_STATIC, nullptr },
	{ "SetBrushResourceToMaterial", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetBrushResourceToMaterial), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetBrushResourceToTexture", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetBrushResourceToTexture), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetColorVisionDeficiencyType", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetColorVisionDeficiencyType), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetFocusToGameViewport", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetFocusToGameViewport), METH_NOARGS | METH_STATIC, nullptr },
	{ "SetHardwareCursor", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetHardwareCursor), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetInputMode_GameAndUIEx", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetInputMode_GameAndUIEx), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetInputMode_GameOnly", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetInputMode_GameOnly), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetInputMode_UIOnlyEx", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetInputMode_UIOnlyEx), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetMousePosition", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetMousePosition), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetUserFocus", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetUserFocus), METH_VARARGS | METH_STATIC, nullptr },
	{ "SetWindowTitleBarCloseButtonActive", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetWindowTitleBarCloseButtonActive), METH_O | METH_STATIC, nullptr },
	{ "SetWindowTitleBarOnCloseClickedDelegate", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetWindowTitleBarOnCloseClickedDelegate), METH_O | METH_STATIC, nullptr },
	{ "SetWindowTitleBarState", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallSetWindowTitleBarState), METH_VARARGS | METH_STATIC, nullptr },
	{ "Unhandled", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallUnhandled), METH_NOARGS | METH_STATIC, nullptr },
	{ "UnlockMouse", UPyCFunctionCast(&FMethods_WidgetBlueprintLibrary::CallUnlockMouse), METH_O | METH_STATIC, nullptr },
	{ nullptr }
};



PyTypeObject* DoInitWrapperWidgetBlueprintLibrary(const UClass* InClass, PyTypeObject* InSuperType, PyObject* InSuperTypes)
{
	if (InClass == nullptr)
	{
		return nullptr;
	}

	if (FUPyWrapperTypeRegistry::Get().HasWrappedClassType(InClass))
	{
		return const_cast<PyTypeObject*>(FUPyWrapperTypeRegistry::Get().GetWrappedClassType(InClass));
	}

	PyTypeObject* PyType = &UPyWrapperWidgetBlueprintLibraryType;
	PyType->tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE;
	PyType->tp_base = InSuperType != nullptr ? InSuperType : &UPyWrapperObjectType;
	PyType->tp_bases = InSuperTypes;
	PyType->tp_methods = FUPyWrapperWidgetBlueprintLibraryPyMethodDefs;

	if (PyType_Ready(PyType) == 0)
	{
		FUPyWrapperTypeRegistry::Get().RegisterWrappedClassType(InClass, PyType);
		return PyType;
	}

	return nullptr;
}

void InitializeUPyWrapperWidgetBlueprintLibrary(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	FUPyWrapperTypeRegistry::Get().RegisterAutoWrappedClassCreateFunc(UWidgetBlueprintLibrary::StaticClass(), DoInitWrapperWidgetBlueprintLibrary);
}

FUPyWrapperWidgetBlueprintLibrary* UPyIsWidgetBlueprintLibrary(PyObject* InSelf)
{
	if (InSelf && PyObject_IsInstance(InSelf, (PyObject*)&UPyWrapperWidgetBlueprintLibraryType))
	{
		return (FUPyWrapperWidgetBlueprintLibrary*)InSelf;
	}
	return nullptr;
}

namespace UPyConversion
{
	FUPyConversionResult Nativize(PyObject* PyObj, UWidgetBlueprintLibrary*& OutVal, const ESetErrorState SetErrorState)
	{
		if (FUPyWrapperWidgetBlueprintLibrary* PyWidgetBlueprintLibrary = UPyIsWidgetBlueprintLibrary(PyObj))
		{
			if (!FUPyWrapperObject::ValidateInternalState(PyWidgetBlueprintLibrary))
			{
				return FUPyConversionResult::Failure();
			}

			OutVal = PyWidgetBlueprintLibrary->ValuePtr();
			return FUPyConversionResult::Success();
		}

		UPYCONVERSION_RETURN(FUPyConversionResult::Failure(), TEXT("Nativize"), *FString::Printf(TEXT("Cannot nativize '%s' as 'UWidgetBlueprintLibrary'"), *UPyUtil::GetFriendlyTypename(PyObj)));
	}
}
