
// This file is automatically generated. Do not edit manually.

#pragma once

{IncludeFiles}

/** Python type for {CppType} */
extern PyTypeObject {PyType};

/** Initialize the {PyType} types and add them to the given Python module */
void {FunctionName}(UPyGenUtil::FNativePythonModule& ModuleInfo);

class {CppType}: public {BaseType}
{
public:

	UNREALPYTHON_API static PyTypeObject* GetPyType()
	{
		return &{PyType};
	}

	UNREALPYTHON_API {RawType}* ValuePtr() const
	{
		return static_cast<{RawType}*>(StructInstance);
	}

	UNREALPYTHON_API static PyObject* CreateInstance(const {RawType}& InValue, const FUPyWrapperOwnerContext& InOwnerContext = FUPyWrapperOwnerContext(), const EUPyConversionMethod InConversionMethod = EUPyConversionMethod::Copy);
};

UNREALPYTHON_API {CppType}* UPyIs{TpName}(PyObject* InSelf);

namespace UPyConversion
{
	UNREALPYTHON_API FUPyConversionResult NativizeStructInstance(PyObject* PyObj, {RawType}& OutVal, const ESetErrorState SetErrorState = ESetErrorState::Yes);
	UNREALPYTHON_API FUPyConversionResult PythonizeStructInstance(const {RawType}& InVal, PyObject*& OutPyObj, const ESetErrorState SetErrorState = ESetErrorState::Yes);
}
