// This file is automatically generated. Do not edit manually.
#include "Wrapper/AutoGen/SlateCore/UPySlateCoreModuleWrapper.h"
#include "Wrapper/AutoGen/SlateCore/Struct/UPyWrapperSlateColor.h"
#include "Wrapper/AutoGen/SlateCore/Struct/UPyWrapperGeometry.h"

void InitializeSlateCoreModuleWrapperTypes(UPyGenUtil::FNativePythonModule& ModuleInfo)
{
	InitializeUPyWrapperSlateColor(ModuleInfo);
	InitializeUPyWrapperGeometry(ModuleInfo);
}
